### ISSUE TITLE
 Add arm64 platform support 

### ISSUE THREAD

**Issue by xin3liang** [openebs/mayastor#1063]
Hi, we are evaluating/verifying Mayastor on arm64 platforms.  But we found that there is no arm64 container images on the docker hub [mayadata repo](https://hub.docker.com/r/mayadata/).
Please provide arm64 container images as well. That will be appreciated！

**Comment by xin3liang** [comment]
FYI, for dependent arm64 Bitnami etcd images. See this [upstream issue](https://github.com/bitnami/charts/issues/7305#issuecomment-1003344728). Bitnami is working on it and there is a workaround to build arm64 images.

**Comment by neoaggelos** [comment]
Here's the code that fails https://github.com/openebs/mayastor/blob/85af174309b45be72cfb36d0630be82bc460154e/mayastor/src/core/env.rs#L682-L697, apparently the spdk subsystem fails to initialize.

Not sure if this is a missing module/configuration, or an issue with arm builds in general.

**Comment by neoaggelos** [comment]
And here's the error in the C code of spdk. https://github.com/openebs/spdk/blob/ec2e6e2b91771abe5136f6f8b19a21130977772c/module/bdev/crypto/vbdev_crypto.c#L384-L391

I really am out of my depth as to what might me missing, I would appreciate any pointers.

**Comment by xin3liang** [comment]
> I've been trying to get arm64 mayastor to work, but I'm getting the following error:
> 
> ```
> # microk8s.kubectl logs -n mayastor mayastor-7vgjh
> Defaulted container "mayastor" out of: mayastor, registration-probe (init), etcd-probe (init), initialize-pool (init)
> [2022-05-12T08:42:53.222263249+00:00  INFO mayastor:mayastor.rs:94] free_pages: 1024 nr_pages: 1024
> [2022-05-12T08:42:53.222373227+00:00  INFO mayastor:mayastor.rs:133] Starting Mayastor version: v1.0.0-117-g77f837aa7f7d
> [2022-05-12T08:42:53.222445241+00:00  INFO mayastor:mayastor.rs:134] kernel io_uring support: yes
> [2022-05-12T08:42:53.222457220+00:00  INFO mayastor:mayastor.rs:138] kernel nvme initiator multipath support: yes
> [2022-05-12T08:42:53.222498991+00:00  INFO mayastor::core::env:env.rs:600] loading mayastor config YAML file /var/local/mayastor/config.yaml
> [2022-05-12T08:42:53.222517255+00:00  INFO mayastor::subsys::config:mod.rs:168] Config file /var/local/mayastor/config.yaml is empty, reverting to default config
> [2022-05-12T08:42:53.222539277+00:00  INFO mayastor::subsys::config::opts:opts.rs:155] Overriding NVMF_TCP_MAX_QUEUE_DEPTH value to '32'
> [2022-05-12T08:42:53.222565803+00:00  INFO mayastor::subsys::config:mod.rs:216] Applying Mayastor configuration settings
> EAL: No available 32768 kB hugepages reported
> EAL: No available 64 kB hugepages reported
> EAL: No available 1048576 kB hugepages reported
> TELEMETRY: No legacy callbacks, legacy socket not created
> [2022-05-12T08:42:53.234421452+00:00  INFO mayastor::core::mempool:mempool.rs:50] Memory pool 'bdev_io_ctx' with 65535 elements (24 bytes size) successfully created
> [2022-05-12T08:42:53.237588030+00:00  INFO mayastor::core::mempool:mempool.rs:50] Memory pool 'nvme_ctrl_io_ctx' with 65535 elements (72 bytes size) successfully created
> [2022-05-12T08:42:53.237614934+00:00  INFO mayastor::core::env:env.rs:649] Total number of cores available: 1
> [2022-05-12T08:42:53.251155428+00:00  INFO mayastor::core::reactor:reactor.rs:175] scheduled init_thread 0xaaaaf2157110 on core:1
> [2022-05-12T08:42:53.251183349+00:00  INFO mayastor::core::reactor:reactor.rs:151] Init thread ID 1
> [2022-05-12T08:42:53.251192358+00:00  INFO mayastor::core::env:env.rs:678] All cores locked and loaded!
> [2022-05-12T08:42:53.331782334+00:00 ERROR mayastor::spdk:vbdev_crypto.c:394] error creating virtual PMD crypto_aesni_mb   
> [2022-05-12T08:42:53.331817205+00:00 ERROR mayastor::spdk:vbdev_crypto.c:1564] Error setting up crypto devices   
> [2022-05-12T08:42:53.331825566+00:00 ERROR mayastor::spdk:bdev.c:1426] bdev modules init failed   
> [2022-05-12T08:42:53.331858566+00:00 ERROR mayastor::spdk:subsystem.c:169] Init subsystem bdev failed   
> thread 'main' panicked at 'assertion failed: receiver.await.unwrap()', mayastor/src/core/env.rs:696:13
> stack backtrace:
>    0: rust_begin_unwind
>              at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
>    1: core::panicking::panic_fmt
>              at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
>    2: core::panicking::panic
>              at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
>    3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>    4: <async_task::runnable::spawn_local::Checked<F> as core::future::future::Future>::poll
>    5: async_task::raw::RawTask<F,T,S>::run
>    6: mayastor::core::reactor::Reactor::poll_once
>    7: mayastor::core::reactor::Reactor::block_on
>    8: mayastor::core::env::MayastorEnvironment::init
>    9: mayastor::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```
> 
> Here are the images I am using. @xin3liang any ideas? Are there any other changes to the upstream manifests that I have missed?


Hi @neoaggelos glad to hear someone care about arm :smile:.  From the log it fails at crypto_aesni_mb init. And this crypto module is Intel only arm doesn't support it now. see https://github.com/openebs/mayastor/pull/1121 for more details there some discuss about it.

And all the arm changes I have linked at this issue, some of them are merged some are not yet. For how to build mayastor data and control plane you can refer my scripts in the description of this  [story](https://linaro.atlassian.net/browse/STOR-35)

**Comment by neoaggelos** [comment]
> Hi @neoaggelos glad to hear someone care about arm :smile:. 

Likewise :) Thank you so much for all the hard work you put into this, it is much appreciated.

> From the log it fails at crypto_aesni_mb init. And this crypto module is Intel only arm doesn't support it now. see https://github.com/openebs/mayastor/pull/1121 for more details there some discuss about it.
> 
> And all the arm changes I have linked at this issue, some of them are merged some are not yet. For how to build mayastor data and control plane you can refer my scripts in the description of this  [story](https://linaro.atlassian.net/browse/STOR-35)

Thanks, I managed to get things building and working. 

Nix is kinda arcane to me, but I got the control plane to build on arm64 (I think everything control-plane related has been merged now so that was easy). For the data plane, I had multiple issues but I got it to build in the end.

As for the error, a random `docker image ls` made me realize that I was using the wrong image (an older one from 2-3 months back). Once I switched to the image from a week ago, the crypto initialization issues went away (it was a matter of `latest` vs `develop` which I initially missed).

FYI, if you are interested in testing things out, we are planning on getting this into MicroK8s 1.24, see https://github.com/canonical/microk8s-core-addons/pull/32.

Thanks again!

**Comment by xin3liang** [comment]
> > Hi @neoaggelos glad to hear someone care about arm 😄.
> 
> Likewise :) Thank you so much for all the hard work you put into this, it is much appreciated.
> 
> > From the log it fails at crypto_aesni_mb init. And this crypto module is Intel only arm doesn't support it now. see #1121 for more details there some discuss about it.
> > And all the arm changes I have linked at this issue, some of them are merged some are not yet. For how to build mayastor data and control plane you can refer my scripts in the description of this  [story](https://linaro.atlassian.net/browse/STOR-35)
> 
> Thanks, I managed to get things building and working.
> 
> Nix is kinda arcane to me, but I got the control plane to build on arm64 (I think everything control-plane related has been merged now so that was easy). For the data plane, I had multiple issues but I got it to build in the end.
> 
> As for the error, a random `docker image ls` made me realize that I was using the wrong image (an older one from 2-3 months back). Once I switched to the image from a week ago, the crypto initialization issues went away (it was a matter of `latest` vs `develop` which I initially missed).
> 
> FYI, if you are interested in testing things out, we are planning on getting this into MicroK8s 1.24, see [canonical/microk8s-core-addons#32](https://github.com/canonical/microk8s-core-addons/pull/32).

Glad you managed to get things working.
Thanks @neoaggelos , this really help me a lot. Because we want to test Mayastor in a multi-node k8s cluster. Microk8s is a good tool for multi-node k8s deployment. :+1:

> 
> Thanks again!

**Comment by Ab-hishek** [comment]
Closing this issue as the fixes mentioned below for this issue have been merged:
1. [mayastor-control-plane: build: add kubectl-plugin build support for arm64CLOSED](https://github.com/openebs/mayastor-control-plane/pull/225) 
2. [spdk-rs: fix: fix arm64 buildCLOSED](https://github.com/mayadata-io/spdk-rs/pull/9) 
3. [spdk: dpdkbuild: Fix Nix DPDK build on arm64 machineCLOSED](https://github.com/openebs/spdk/pull/16) 
4. [mayastor: fix(build): fix arm64 buildCLOSED](https://github.com/openebs/mayastor/pull/1121) 
5. [mayastor-control-plane: fix: fix run on arm64OPEN](https://github.com/openebs/mayastor-control-plane/pull/249)

**Comment by xin3liang** [comment]
Separate this Issue, make it arm64 support only and for arm64 images release create another issue to track it.
https://github.com/openebs/mayastor/issues/1147
