### ISSUE TITLE
Error during helm install: etcd missing in charts/

### ISSUE THREAD

**Issue by hickersonj** [openebs/mayastor#1088]
**Describe the bug**
When trying to deploy mayastor via the helm instructions it throws a missing dependency error for etcd.

**To Reproduce**
```
helm install mayastor mayastor/chart --namespace=mayastor --create-namespace
Error: INSTALLATION FAILED: found in Chart.yaml, but missing in charts/ directory: etcd
```
**Expected behavior**
Installs mayastor

** OS info (please complete the following information):**
 - Distro: [Fedora 33]
 - Kernel version - 5.12.9-200.fc33.x86_64
 - MayaStor revision or container image - pulled from github -b develop

**Additional context**
I added the etcd repo ` helm repo add etcd https://charts.bitnami.com/bitnami` but that didn't resolve it.

**Comment by tiagolobocastro** [comment]
Could you please try running `helm dependency update chart` (assuming you're at the root of the repo)

**Comment by hickersonj** [comment]
That got me further thanks!  Didn't know about the dependency update option.
However, now it looks like perhaps a template is not configured correctly, or maybe I need to add a value for `pool-on-NODE_NAME`?
```
helm install mayastor mayastor/chart --namespace=mayastor --create-namespace
Error: INSTALLATION FAILED: MayastorPool.openebs.io "pool-on-NODE_NAME" is invalid: metadata.name: Invalid value: "pool-on-NODE_NAME": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Comment by tiagolobocastro** [comment]
I guess that was just an example file, you can delete that file and add your own pool once the install is complete. By the way this only install mayastor, you'll also have to install the [control-plane](https://github.com/openebs/mayastor-control-plane) to be able to use mayastor:

**Comment by hickersonj** [comment]
Ok that makes more sense because when I did the helm install it was missing quite a bit.  I can try this as well, but from the looks of it, helm is not the preferred method yet.
