### ISSUE TITLE
ARM64 support for Mayastor components

### ISSUE THREAD

**Issue by AlexsJones** [openebs/mayastor#1107]
**Describe the bug**

When installing `Mayastor` on arm64 based hardware e.g. Macbook M1, several components have exec format errors due to not being compiled for multiarch. 

- `docker.io/bitnami/bitnami-shell:10`
- `connecteverything/nats-server-config-reloader:0.6.0`

**To Reproduce**

- `microk8s start` on a Macbook pro through multipass ( e.g. `brew install ubuntu/microk8s/microk8s` ) 
- Modify the VM to enable huge pages and pre-requisites
- Follow the Mayastor install guide https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor

**Expected behavior**
All pods will go into a running state.

**Screenshots**
<img width="1355" alt="Screenshot 2022-02-21 at 10 43 15" src="https://user-images.githubusercontent.com/1235925/154939614-d362d937-6e6b-4dfa-99ed-d1ccaca24acc.png">

** OS info (please complete the following information):**
 - Distro: Ubuntu 18.04 LTS ARM64

**Additional context**

**Comment by xin3liang** [comment]
@AlexsJones I build arm images on myself, see bellow link for details deployment images.

**Comment by xin3liang** [comment]
And I record the arm support patches here: https://github.com/openebs/mayastor/issues/1063

**Comment by Ab-hishek** [comment]
Closing this issue as the fixes mentioned below for this issue have been merged:
1. [mayastor-control-plane: build: add kubectl-plugin build support for arm64](https://github.com/openebs/mayastor-control-plane/pull/225) 
2. [spdk-rs: fix: fix arm64 build](https://github.com/mayadata-io/spdk-rs/pull/9) 
3. [spdk: dpdkbuild: Fix Nix DPDK build on arm64 machine](https://github.com/openebs/spdk/pull/16) 
4. [mayastor: fix(build): fix arm64 build](https://github.com/openebs/mayastor/pull/1121) 
5. [mayastor-control-plane: fix: fix run on arm64](https://github.com/openebs/mayastor-control-plane/pull/249)

**Comment by jokeyrhyme** [comment]
- I've got a [talos](https://www.talos.dev/) cluster on Raspberry Pi 4B nodes, running k8s 1.24.2
- I noticed that 3.3.0 is out, yay! https://github.com/openebs/openebs/releases/tag/v3.3.0
- the release notes mention "mayastor 1.0.1"
- so I work through https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor , but hard-coding "v1.0.1" in the raw GitHub URLs, e.g. `kubectl apply --filename https://raw.githubusercontent.com/openebs/mayastor-control-plane/v1.0.1/deploy/mayastorpoolcrd.yaml`
- I get to the step where I run `kubectl apply --filename https://raw.githubusercontent.com/openebs/mayastor/v1.0.1/deploy/nats-deployment.yaml`
- and when I describe pod/nats-0, the "nats" container (with image "nats:2.1.7-alpine3.11") is running just fine
- but the "reloader" container (with image "connecteverything/nats-server-config-reloader:0.6.0" has the following error in its logs:

> exec /usr/local/bin/nats-server-config-reloader: exec format error

- it's possible that I've made some mistakes here, but I'm wondering if maybe "connecteverything/nats-server-config-reloader:0.6.0" is not yet multi-arch?

**Comment by jokeyrhyme** [comment]
- yeah, looks like connecteverything/nats-server-config-reloader:0.6.0 was pushed 3 years ago and is only for linux/amd64: https://hub.docker.com/r/connecteverything/nats-server-config-reloader/tags
