### ISSUE TITLE
If a volume is permanently lost, can access be restored through the replica?

### ISSUE THREAD

**Issue by buzzers** [openebs/mayastor#1120]
If the node on which a volume resides is permanently lost, the volume will be inaccessible as described in the known limitations of the documentation. So is there a way to restore access at this point?

**Comment by gila** [comment]
Depends a bit on what is lost where exactly. If volume here is the PVC being consumed then the replicas (depending on the number) can be accessed directly; without the need for nexus in between. Is this what you mean?

**Comment by buzzers** [comment]
>However a Mayastor volume is currently accessible to an application only via a single target instance (NVMe-oF) of a single Mayastor pod. If that pod terminates (through the loss of the worker node on which it's scheduled, execution failure etc.) then there will be no viable I/O path to any remaining healthy replicas and access to data on the volume cannot be maintained. Mayastor will try to create the nexus on the same node where the application will be running if possible. That avoids the problem of nexus being inaccessible for the application if the node is down. See ["local" storage class parameter description](https://mayastor.gitbook.io/introduction/reference/storage-class-parameters) for more in-depth explanation.

I can't quite understand this sentence. My understanding of "no high availability" is that if I permanently lose the PV's master (what I call it), then I won't be able to access my data, even if there are other replicas. Is this correct?

**Comment by gila** [comment]
No, the thing you refer to as "master" is just a connection endpoint to the replicas. Those master connection endpoints (which is called a nexus) is stateless and can be provisioned again by the control plane. 

What I was trying to convey is that even without a nexus you could still access you date but it would be a bit more involving. 

A nexus connects to a replica over nvmf. A pod connect through the nexus. But with some manual work you can directly connect to a replica. HTH

**Comment by buzzers** [comment]
In this case, what scenario does "not highly available" in the documentation refer to?
