### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by fzyzcjy** [openebs/mayastor#1130]
Hi thanks for the lib - I wonder whether it is ready for production?

**Comment by silverhandy** [comment]
There is the same question I have, 
from the Mayastor 1.0.0 release notes: With this release Mayastor is considered graduated from pre-release / beta status.
so is that means Mayastor declared with GA?

**Comment by GlennBullingham** [comment]
@silverhandy  That is correct.  Version 1.0.0 is a GA release and Mayastor is now considered by the project's maintainers to have exited the beta phase.

We recommend deploying the latest release, v1.0.1 as this contains fixes for some issues identified after the release of v1.0.0
