### ISSUE TITLE
Pods stuck in Init

### ISSUE THREAD

**Issue by wibed** [openebs/mayastor#1150]
![image](https://user-images.githubusercontent.com/69305089/176630247-5ab0809b-68b6-4c45-8a91-dac4f3d8373b.png)

following the documentation 
adding flannel, for i assumed this was the source, but wasnt.
nor did restarting the node help

the pods are stuck in their init phase.

**Comment by GlennBullingham** [comment]
Looks to me as if the etcd instance isn't converged (only 1 pod of 3 running, 2 pending) and that's causing the control plane init containers to fail.

I'd start with working out why two of the etcd pods are still in the pending state.

**Comment by wibed** [comment]
it seems running on a single note it cant archive "quorum" or whatever it is
called and timesout on healthcheck.sh


adding 3 more nodes i am waiting for those containers to initialize.

![image](https://user-images.githubusercontent.com/69305089/176660150-31c0423b-42fa-4430-98c0-4e6528130340.png)
