### ISSUE TITLE
Error when used in lxc containers: insufficient free pages available PAGES_NEEDED=1024 nr_pages=1024

### ISSUE THREAD

**Issue by ivanix1** [openebs/mayastor#1159]
Hello,
I am trying to setup a microk8s cluster using 3 LXD containers for the cluster.
The cluster itself comes up, but when i try to enable mayastor  with 20G, only node volume (node) come online;
Two other mayastor-xxxx pods CrashLoopBackOff and the error shows in the logs

`insufficient free pages available PAGES_NEEDED=1024 nr_pages=1024`

I followed the guideline https://microk8s.io/docs/addon-mayastor 
As best I can tell I do have hugepages set to 1024 on both the host machine and within each lxc container.
I looked within the LXD documentation and could not find any limit setting or other hint.

The host machine is ubuntu 20.04 with 32GB and 8 core intel cpu.| 
There is 300GB of free space. Backend storage for containers is dir.
Containers also use ubuntu 20.04
microk8s   version v1.24.0
kernel 5.4.0-122-generic
Any suggestions much appreciated.

**Comment by datacore-tilangovan** [comment]
Hello,

Can you run this command on hostmachine & lxc container and show us the output please. 

#grep HugePages /proc/meminfo

**Comment by vharsh** [comment]
Hi @ivanix1 it seems this issue has been fixed in a162431a1, which will go in 1.0.2 release of MayaStor. I'd have to check this in a bit as to how this gets into MicroK8s addons and get back to you.

**Comment by tiagolobocastro** [comment]
I don't think that is right @vharsh, that change did not make it to the 1.0.2...

**Comment by dsharma-dc** [comment]
I'm guessing this issue is resolved, or not an issue anymore. Please revert back/reopen the issue if it still persists.
Sometimes the system caches need to be cleaned up before setting up number of hugepages, otherwise system isn't able to reserve the required number of hugepages. The way to clean up caches is:

` sync; echo 3 > /proc/sys/vm/drop_caches`
