### ISSUE TITLE
Write Performance with Network Latency

### ISSUE THREAD

**Issue by Daxcor69** [openebs/mayastor#1165]
I am looking for clarification on write performance on a single replica to slower class of physical drives.

Primary storage node, would be a nvme drive based storage node.
Replica storage node, large sata drive.  Having this replica storage node in a different geo location.

The question is two fold.  First, is the user facing write performance the slowest write operation. In this case, the replica storage node.  Or  does the primary write happen and then the replica follows, thus having the performance of the primary node using nvme drive.

Second, is there a way to designate the replica location?  I would be using a service mesh in my k8s cluster to have a replica storage node in another DC.

Thanks
Brad

**Comment by GlennBullingham** [comment]
Mayastor's replication is "synchronous with respect to the caller".  That is to say, whilst writes are issued by the volume target (nexus) to its children (replicas) in parallel,  completion for a particular I/O is not returned to the caller until the nexus receives completions for the corresponding outstanding writes to all children.  Ergo, the performance characteristics of the volume will be set by the lowest common denominator - the slowest device / greatest network latency.  This behaviour is documented in the architecture section of the : [Mayastor user docs](https://mayastor.gitbook.io/introduction/reference/i-o-path-description)

To set that in some context, to use the full bandwidth of a high performance NVMe device such, as Intel's Optane, requires latency to be in the order of that of a 100GbE network.  Replication between geographically distributed data centres may not meet that.  The design of Mayastor's current mirroring implementation is aimed at replication within a single k8s cluster and within a single data centre.

There is currently no way for a user to designate replica placement, a control plane heuristic handle this automatically.  The maintainers, in conjunction with some interested community members, are currently looking into how best to implement topology awareness / policy-driven replica placement.

**Comment by Daxcor69** [comment]
Thank you for the clarification, I am sorry I didn't see this section in the docs. I did read them. I promise. Can't wait to get your file system in production.

Thanks
