### ISSUE TITLE
Thin Provisioning

### ISSUE THREAD

**Issue by Daxcor69** [openebs/mayastor#1185]
My use case is I have over a 1000 customers, that each are allocated a certain amount of storage space.  Actual used storage is currently 3 T.  When I do the calculated allocated space it is closer to 10 T.  For my use case, there is a significant cost implications for "Thick" provisioning.  At this point I would not be able to have replicated storage.  I have no idea what it would take to have the project incorporate this feature.  I don't make the request lightly.  I saw in the docs, that it is being considered.  Just would like to know if it is a possibility and if so.. what is the % chance it would come to light.

Thanks
Brad

**Comment by GlennBullingham** [comment]
@Daxcor69 This is very much a possibility, as it is currently being worked on.  Other community members have previously raised the same/similar use cases and so the feature has been on the wish list for a while.

Practically speaking, code for this is being committed now and we currently expect it to be featured in an official release around October this year.

**Comment by Daxcor69** [comment]
That is totally amazing.  I can't wait.  These two features   thing provisioning and dedicated network  were the two deciding issues that I struggled with as to weather or not to go with cepf as a backend.  thank you again for all your teams hard work.

**Comment by GlennBullingham** [comment]
You're welcome, it's good to receive feedback that we're on the right path and actually adding value to the project for its users.

Would you like to try for a third feature request whilst your luck is still in? 😃

**Comment by tiagolobocastro** [comment]
Thin-provisioning has been released on v2.2.
