### ISSUE TITLE
Recover pool

### ISSUE THREAD

**Issue by sgerme** [openebs/mayastor#1199]
**Is your feature request related to a problem? Please describe.**
Hi, I have a cluster running Talos 0.14 on bare metal using NVMe SSDs.
After a crash of one of the nodes, I re-deployed it with the same name. but the pool is not recognized anymore.

**Describe the solution you'd like**
a way to start a normal Linux, to recover all the data. When I try to mount the disk, it is not mountable since it does not appear as a valid format.

**Describe alternatives you've considered**
Try to recreate the pool. But this pool appears as status "unknown"

**Additional context**
two bare metal servers, with two NVMe SSD, one for the talos system, another dedicated to mayastor. I try to recover data from this second drive.

thanks for helping !

**Comment by tiagolobocastro** [comment]
What version of mayastor are you running?
I suspect you've hit a pool operator bug, which is causing the pool to simply appear as "unknown".
Could you please run `kubectl-mayastor get pools` and check if the pool is also "unkown" there?

**Comment by sgerme** [comment]
I am running on ARM and never succeed to run mayastor binaries :( 
I'll try on another one. 

``` kubectl-mayastor get pools
zsh: exec format error: kubectl-mayastor

**Comment by tiagolobocastro** [comment]
Oh, we don't have a published arm version. You can try building it yourself from the [control-plane repo](https://github.com/openebs/mayastor-control-plane) from the 1 release branch, if that's what you're running:
`nix-build -A utils.release.linux-musl.kubectl-plugin`

**Comment by tiagolobocastro** [comment]
@sgerme, to recreate the pool I think you can delete the CR and recreate it. If delete is stuck you may remove the finalizer - this is safe, we don't delete any replicas on CR delete, only the pool if it has no replicas known to the control-plane.

**Comment by sgerme** [comment]
I have finally deleted everything and recreate the pools. I've downloaded backups. Thanks anyway :)
