### ISSUE TITLE
Deploy Mayastor: Data Plane 404

### ISSUE THREAD

**Issue by lnsyyj** [openebs/mayastor#1232]
Hello everyone,

I follow the documentation to deploy mayastor in k8s, this data-plane
Chapter Page 404.
https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor#data-plane
````
kubectl apply -f https://raw.githubusercontent.com/openebs/mayastor/master/v1.0.2/mayastor-daemonset.yaml
````

url return 404
```
https://raw.githubusercontent.com/openebs/mayastor/master/v1.0.2/mayastor-daemonset.yaml   
```

**Comment by lnsyyj** [comment]
The documentation has been updated, but v1.0.3 still returns 404, the file does not exist.
```
https://raw.githubusercontent.com/openebs/mayastor/v1.0.3/mayastor-daemonset.yaml
```

**Comment by GlennBullingham** [comment]
resolved by: https://github.com/openebs/mayastor-docs/pull/76
