### ISSUE TITLE
Upgrade not supported, re-install required - is an issue

### ISSUE THREAD

**Issue by rhrytskiv** [openebs/mayastor#1233]
**Is your feature request related to a problem? Please describe.**
Hi, we have Mayastor 1.0.1 in our cluster, and we want to keep it up to date. Now we see that we can upgrade to 1.0.2 but for 1.0.3 it says "Upgrades from versions of Mayastor prior to v1.0.3 are not supported. Any release earlier than v1.0.3 should be removed prior to installing this version.".
Is this a mistake? Or if not, what version should be considered stable? Because if I understand correctly re-install would require us to delete Mayastor resources and that will result in data loss, isn't it?

**Describe the solution you'd like**
I'd like to be able to upgrade without data loss.

**Describe alternatives you've considered**

**Additional context**

**Comment by GlennBullingham** [comment]
It's a typo in the release notes, probably the result of an overly aggressive find & replace.  

It should read "Upgrades from versions of Mayastor **prior to v1.0.0** are not supported", as per the previous release (v1.0.2).  We'll correct it shortly.

Sorry for any inconvenience.

**Comment by GlennBullingham** [comment]
Fixed.
