### ISSUE TITLE
Mayastor appears not to work on GKE

### ISSUE THREAD

**Issue by inviscid** [openebs/mayastor#1268]
**Are you reporting an issue with existing content?**
The current documentation provides a step by step guide for deploying and testing mayastor on a generic Kubernetes cluster.  The prerequisites alone make it seem incompatible with GKE since (as of this post) the latest kernel version available is 5.4 in both the Container Optimized OS and Ubuntu with containerd options for node images.

After deciding to forge ahead with the install on GKE the first thing you run into is the need to create a daemonset to setup the hugepages and restart the kubelet.  It would have been very handy to have an example of this since it was quite painful figuring it out.

Once everything is installed and all services, pods, daemonsets, etc.. are deployed and running, the MSPs all show in an `Unknown` state.  There is nothing to indicate what to do about this and there appears to be no error log information available to troubleshoot this.  While the GKE nodes are running on kernel v5.4, it does not seem to be suffering from the restart problem indicated in the known issues area.  Since the MSPs are in an `Unknown` state the PVCs are never bound to a PV when trying to deploy the fio test.

The impacted pages are:
https://mayastor.gitbook.io/introduction/quickstart/prerequisites
https://mayastor.gitbook.io/introduction/v/develop/quickstart/deploy-mayastor
https://mayastor.gitbook.io/introduction/v/develop/quickstart/configure-mayastor
https://mayastor.gitbook.io/introduction/v/develop/quickstart/deploy-a-test-application

**Are you proposing new content, or a change to the existing documentation layout or structure?**
The documentation doesn't appear to work for GKE.  I would propose a documentation update that allows creation of reasonable default mayastor cluster using local NVMe drives on the GKE nodes without needing to manually configure each node by hand.  This would include node preparation daemonsets as well as which GKE image is suitable (e.g. container optimized OS or ubuntu with containerd).

**Comment by tiagolobocastro** [comment]
@avishnu do we have any internal documentation/notes for GKE?

@inviscid would you be able to take a support dump and send us the tar?
`kubectl mayastor dump system`
(btw the develop branch docs are not up to date, you don't need to open ports for the kubectl-mayastor plugin anymore..)

**Comment by avishnu** [comment]
@inviscid , what's the mayastor release version, you have installed? Have you checked for all the pre-requisites listed [here](https://mayastor.gitbook.io/introduction/quickstart/prerequisites)? You should try the Ubuntu with containerd for the GKE image. Please provide the outputs requested by @tiagolobocastro .
@tiagolobocastro We don't have any GKE-specific documentation AFAIK.

**Comment by tiagolobocastro** [comment]
I suspect this is the same as https://github.com/openebs/mayastor/issues/1144 which has been fixed on develop but we've not back ported.
