### ISSUE TITLE
Define the relationship between disk pools and storage classes

### ISSUE THREAD

**Issue by robjcaskey** [openebs/mayastor#1272]
**Is your feature request related to a problem? Please describe.**
I have nvme storage and ramdisk storage and would like to be able to ensure the volume I create points to the expected type of storage but mayastor doesn't have a way to do this.

**Describe the solution you'd like**
Allow specifying a diskPoolSelector on the storage class and restrict which DiskPools can can participate in a storage class via arbitrary label selectors: e.g.

```
diskPoolSelector:
    my-media-type: ram
```

**Additional context**
 I'm not familiar enough with the architecture or roadmap to make a more specific suggestion but was encouraged to file an issue on slack.

**Comment by tiagolobocastro** [comment]
Tracked in #1545
