### ISSUE TITLE
Mayastor IO Engine pods fail to boot due to grpc client connection error

### ISSUE THREAD

**Issue by hiattp** [openebs/mayastor#1273]
**Describe the bug**
While attempting to install mayastor `2.0.0-develop` via the helm chart, everything works except for the `mayastor-io-engine` pods, which appear to have an issue with the grpc client:

```
  2022-12-26T22:45:29.485461Z ERROR exporter::pool::client::grpc_client: Grpc client connection error, retrying after 10s, error: transport error
    at exporter/src/pool/client/grpc_client.rs:122
```

Happy to grab more logs somewhere though I'm at a loss of where to look for anything that might be more helpful. I thought perhaps it might be a networking issue (i.e. something about [the ports](https://mayastor.gitbook.io/introduction/v/develop/quickstart/prerequisites#networking-requirements) being used) but nothing else is running on the cluster. Perhaps there is a permission/rbac config missing that isn't already installed by helm?

**To Reproduce**
Deploy mayastor via the `develop` docs [here](https://mayastor.gitbook.io/introduction/v/develop/quickstart/preparing-the-cluster) using helm.

**Expected behavior**
Should see all Running pods in `kubectl get pods -n mayastor` after install.

**Screenshots**

<img width="1386" alt="Screenshot 2022-12-26 at 3 42 50 PM" src="https://user-images.githubusercontent.com/571459/209587131-ce94baf6-09cb-45ba-ab7b-b006c403a64a.png">

<img width="864" alt="Screenshot 2022-12-26 at 3 42 27 PM" src="https://user-images.githubusercontent.com/571459/209587221-a51f7b32-27a3-4de3-97bb-849e6a66f443.png">

<img width="1476" alt="Screenshot 2022-12-26 at 3 43 21 PM" src="https://user-images.githubusercontent.com/571459/209587232-133ef971-bd27-4c43-b3a1-c8fe18330345.png">

** OS info (please complete the following information):**

Distro: Talos Linux v1.3.0
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.2
MayaStor revision or container image: 2.0.0-develop

**Additional context**
Note that Mayastor 1.0 was working just fine on this cluster. I removed all mayastor 1.0 components and am attempting to install 2.0.

**Comment by tiagolobocastro** [comment]
Seems there may be a race between the io-engine and the exporter, if the exporter starts first it will fail to connect to the io-engine... but anyway it should eventually connect so this is odd.
Can you run `kubectl-mayastor system dump`and attach the tar?

**Comment by hiattp** [comment]
Definitely, though not sure I'm using the correct version of the `kubectl-mayastor` plugin. I'm using [1.0.5](https://github.com/openebs/mayastor-control-plane/releases/tag/v1.0.5), but it doesn't look like that has a `system dump` command? Sorry if I'm missing something obvious here 🙁 

Running:

```bash
docker run --rm --name kubectl -v /Users/admin/.kube/config:/.kube/config -v /Users/admin/Downloads/kubectl-mayastor:/bin/kubectl-mayastor bitnami/kubectl:latest mayastor system dump
```

Returns:

```bash
error: Found argument 'system' which wasn't expected, or isn't valid in this context
```

Despite the plugin apparently working correctly:

```bash
% docker run --rm --name kubectl -v /Users/admin/.kube/config:/.kube/config -v /Users/admin/Downloads/kubectl-mayastor:/bin/kubectl-mayastor bitnami/kubectl:latest mayastor -V
kubectl-plugin 1.0.0
```

**Comment by tiagolobocastro** [comment]
Since you're using develop, you'll need to download it from the develop: https://github.com/openebs/mayastor-extensions/actions/runs/3765007135

**Comment by hiattp** [comment]
Makes sense, thanks! Here's the system dump:

[mayastor-2023-01-01--21-15-25-UTC.tar.gz](https://github.com/openebs/mayastor/files/10329464/mayastor-2023-01-01--21-15-25-UTC.tar.gz)

**Comment by hiattp** [comment]
Looks like it chokes when trying to look up the number of hugepages [here](https://github.com/openebs/mayastor/blob/d8792f7180a53c84f3121cbb3036021c0c234127/io-engine/src/bin/io-engine.rs#L106). The 2048kB hugepages file at `/sys/kernel/mm/hugepages/hugepages-2048kB/hr_hugepages` is available, but 1g pages are not:

<img width="1009" alt="Screenshot 2023-01-01 at 5 26 26 PM" src="https://user-images.githubusercontent.com/571459/210186305-5ed0ade6-ec1e-4792-b851-b9fefff7f5fc.png">

**Comment by hiattp** [comment]
Hey @tiagolobocastro, resurfacing this now that the post-holiday frenzy has died down. Would it be kosher if I submitted a PR to allow that 1Gb check to fallback to "0" in case 1Gb hugepages aren't enabled? Or will Mayastor be requiring 1Gb hugepages to be enabled going forward even if set to 0?

**Comment by tiagolobocastro** [comment]
Hey @hiattp we don't have any such requirements so a PR for what you suggest would be welcome :) thank you

**Comment by hiattp** [comment]
Cool thanks @tiagolobocastro I took a stab in https://github.com/openebs/mayastor/pull/1284
