### ISSUE TITLE
csi-node is unable to find mount during statefulset scale in

### ISSUE THREAD

**Issue by nearora-msft** [openebs/mayastor#1274]
**Describe the bug**
We are running some scale tests with mayastor and mayastor-control-plane on AKS. When the number of pods per node is large(~80), there are some issues while scaling in and the pods remain in Terminating state.

This happens because, the find_mount check [here ](https://github.com/openebs/mayastor-control-plane/blob/develop/control-plane/csi-driver/src/bin/node/filesystem_vol.rs#L322)returns false, even though the target mount is there in the /proc/mounts file.
As a result, we run into : "Device or resource busy (os error 16)" errors on the csi-node when the csi-node tries to remove the directory here: 
https://github.com/openebs/mayastor-control-plane/blob/develop/control-plane/csi-driver/src/bin/node/filesystem_vol.rs#L326

**To Reproduce**

**Expected behavior**
find_mount should return true when the mount record is present in /proc/mounts

**Screenshots**

** OS info (please complete the following information):**
 - Distro: [e.g. NixOS]
 - Kernel version
 - MayaStor revision or container image

**Additional context**
Related PR: https://github.com/openebs/mayastor-control-plane/pull/413

**Comment by tiagolobocastro** [comment]
Hi, @nearora-msft do you remember what kernel version this was on?
https://github.com/torvalds/linux/commit/9f6c61f96f2d97cbb5f7fa85607bc398f843ff0f which could potentially explain this?

**Comment by nearora-msft** [comment]
> Hi, @nearora-msft do you remember what kernel version this was on? [torvalds/linux@9f6c61f](https://github.com/torvalds/linux/commit/9f6c61f96f2d97cbb5f7fa85607bc398f843ff0f) which could potentially explain this?

Sorry @tiagolobocastro , I don't remember and don't have it recorded either :( . Nonetheless, this commit seems to explain the issue.
