### ISSUE TITLE
Can the volumeDevices devicePath parameter in the fio.yaml configuration file control the name of the pv mounted on the client?

### ISSUE THREAD

**Issue by daming6** [openebs/mayastor#1304]
I intend to use the volumeDevices devicePath parameter in the fio.yaml configuration file to control the name of the persistent volume mounted on a client. For example, here - devicePath writes **/dev/nvme5n1**, but it actually generates **nvme6n1** on the client. I found that the name of pv is automatically generated by the client, adding one at a time. For example, my client already has nvme0n1 nvme1n1 nvme2n1 nvme3n1 nvme4n1 nvme5n1, so the automatically generated name is nvme6n1.
So can the volumeDevices devicePath parameter in the fio.yaml configuration file control the name of the pv mounted on the client? Does this belong to program BUG?
![image](https://user-images.githubusercontent.com/57066327/215649850-56f8028a-306a-40ef-b24e-61c32685bbe2.png)

**Comment by tiagolobocastro** [comment]
You cannot control which nvme device is used like that. Might be better to avoid using nvme naming altogether there, ex: /dev/fiovolume to avoid confusion.

**Comment by daming6** [comment]
> You cannot control which nvme device is used like that. Might be better to avoid using nvme naming altogether there, ex: /dev/fiovolume to avoid confusion.

Thank you very much for your answer.
