### ISSUE TITLE
Basic Troubleshooting: Disaster Recovery for etcd

### ISSUE THREAD

**Issue by laibe** [openebs/mayastor#1318]
I suggest adding additional documentation of what users have to do in case of losing a worker node with mayastor-etcd running on it.
Assuming mayastor 2.0 was deployed with `storageClass=openebs-hostpath` there are some manual steps involved to heal etcd. The below is a suggestion but would need to be tested on different setups to confirm this works for most users. 

Assumption: worker-node has hard shutdown and all data on the hostpath is lost. 

Steps to recover:

1. Edit the `mayastor-etcd` Statefulset from `new` to `existing`: `kubectl edit sts mayastor-etcd -n mayastor`  
```yaml
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: existing
```
2. Manually remove the old etcd member, for example by opening a shell within a still running pod:
```bash
kubectl -n mayastor exec -ti mayastor-etcd-1 bash
etcdctl member list --write-out=table
etcdctl member remove <member_id>
```
3. Delete the pvc linked to the lost mayastor-etcd pod:
```bash
kubectl delete pvc data-mayastor-etcd-0 -n mayastor
```
4. Delete the lost pod:
```bash
kubectl delete pod mayastor-etcd-0 -n mayastor
```
5. If a new worker has joined the cluster, a new mayastor-etcd pod should now be deployed to it and join the existing cluster.
6. etcd should now be back to it's predefined replica count and in healthy state

**Comment by tiagolobocastro** [comment]
Thanks for raising this @laibe, we'll aim to test this scenario and add it to the gitbook.

**Comment by Sapp00** [comment]
If I follow your steps, @laibe , the pod cannot be started because the pvc cannot be bound again (storageclass.storage.k8s.io "manual" not found).

kubectl get pvc
```
NAME                   STATUS    VOLUME          CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-mayastor-etcd-0   Bound     etcd-volume-1   2Gi        RWO            manual         31h
data-mayastor-etcd-1   Bound     etcd-volume-0   2Gi        RWO            manual         31h
data-mayastor-etcd-2   Pending                                             manual         2m53s
```

What is weird about that:
```
k get mayastorpool
NAME            NODE           STATUS   CAPACITY       USED          AVAILABLE
pool-worker-1   k8s-worker01   Online   429073104896   10737418240   418335686656
pool-worker-2   k8s-worker02   Online   429073104896   0             429073104896
pool-worker-3   k8s-worker03   Online   429073104896   10737418240   418335686656
```

While only two nodes have etcd running, 3 pools are marked as up - no error state.

**Comment by laibe** [comment]
It looks like you've installed Mayastor with `storageClass: manual`. The steps are an example for `storageClass=openebs-hostpath`. You might also need to add  `--set etcd.podAntiAffinityPreset=soft`  to the helm installation command. E.g.:

```
helm install mayastor mayastor/mayastor -n mayastor --set="etcd.replicaCount=3,etcd.persistence.storageClass=openebs-hostpath,etcd.podAntiAffinityPreset=soft" --version 2.0.0
```

**Comment by tiagolobocastro** [comment]
We've got a PR on the docs: https://github.com/openebs/mayastor-docs/pull/141 which relates to this.

**Comment by tiagolobocastro** [comment]
docs have been updated
