### ISSUE TITLE
Does mayastor2.0 support creating diskpool with HDD?

### ISSUE THREAD

**Issue by daming6** [openebs/mayastor#1319]
It is introduced in the official document that disks other than nvme disks can also run. 
https://mayastor.gitbook.io/introduction/
**While Mayastor utilizes NVMe-oF it does not require NVMe devices or cloud volumes to operate and can work well with other device types.**
I used HDD to test. I could create a pool on the server side but could not mount it to the client side. So does mayastor now support creating pools with HDD? If not, what is the reason?

**Comment by avishnu** [comment]
@daming6 , Have you checked the docs at https://mayastor.gitbook.io/introduction/quickstart/configure-mayastor and https://mayastor.gitbook.io/introduction/quickstart/deploy-a-test-application?

**Comment by daming6** [comment]
> @daming6 , Have you checked the docs at https://mayastor.gitbook.io/introduction/quickstart/configure-mayastor and https://mayastor.gitbook.io/introduction/quickstart/deploy-a-test-application?

@avishnu ,I read the document you mentioned. The disk types supported by the pool include asynchronous disk, io_ uring and Disk (non PCI) with disk-by-guid reference (Best Practice). HDD is not an asynchronous disk, so it is not supported. But I have a question, what is Disk (non PCI) with disk-by-guid reference (Best Practice)? 
![image](https://user-images.githubusercontent.com/57066327/218661351-2cc64457-f5d8-4068-9715-a41b233b5986.png)

Thank you very much for your reply.

**Comment by tiagolobocastro** [comment]
Hi @daming6 AIO and IO_URING are not disk types, but rather IO interfaces to access a "disk". You can use HDD no problem, but note your performance will be limited by the disk you use.

**Comment by daming6** [comment]
> Hi @daming6 AIO and IO_URING are not disk types, but rather IO interfaces to access a "disk". You can use HDD no problem, but note your performance will be limited by the disk you use.

Hi, @tiagolobocastro. When I use HDD to create a diskpool, I can successfully create it, but the volume **cannot** be successfully mounted to the client for use. Have you ever encountered similar problems?

**Comment by tiagolobocastro** [comment]
Can you please take a support bundle are share with us?
`kubectl-mayastor dump system`

**Comment by tiagolobocastro** [comment]
Please reopen if you'd like further assistance.
