### ISSUE TITLE
Run Mayastor on a node with a single disk

### ISSUE THREAD

**Issue by darox** [openebs/mayastor#1332]
This is more of a question than a feature request. Is there any possibility of running Mayastor on a node with a single NVME disk where the OS is also installed?  From what I understood from the docs, this is not supported as a whole drive will be formatted when provisioned with Mayastor.

Thanks

**Comment by tiagolobocastro** [comment]
You could create a separate partition just for mayastor on the disk. Then configure the mayastor pool to use the partition rather than the whole disk.

**Comment by darox** [comment]
> You could create a separate partition just for mayastor on the disk. Then configure the mayastor pool to use the partition rather than the whole disk.

Nice, I thought this won't work. Will definitely try it. Thank you.

**Comment by darox** [comment]
So this doesn't work. It screws up the whole disk, and the machine can't boot anymore.

**Comment by tiagolobocastro** [comment]
@darox were you able to get this working in the end?

**Comment by darox** [comment]
No, it screwed up the whole disk.  So I assume it's not something that is supported.

**Comment by tiagolobocastro** [comment]
It should work as long as you create the pool with the correct partition. How did you create the pool?

**Comment by darox** [comment]
That's what I did. I have created the pool via CRD and after a few minutes the node wasn't responding anymore, because the system partition was screwed.

**Comment by tiagolobocastro** [comment]
Could you paste the CR of the pool you've created if you still have it?
Did you partition the disk properly? IE the damage could have been done even before we created the pool etc

**Comment by darox** [comment]
Sure:
```
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: kube-worker-3
  namespace: mayastor
spec:
  node: kube-worker-3
  disks: ["/dev/nvme1n2"]
```

I even bought a fresh new disk, but the same has happened.

**Comment by tiagolobocastro** [comment]
How does the partition table look like?
Btw, which version are you running? That seems v1?

**Comment by darox** [comment]
I don't have this anymore.

**Comment by tiagolobocastro** [comment]
I tested on my cluster and seems to work fine. If we provide the pool with the correct partition I can't see how we could  corrupt other partitions but there may be bugs :) so please reopen if you ever try this again, thanks!

**Comment by darox** [comment]
Good to know. I will try again, as soon as mayastor is officially available on arm machines.
