### ISSUE TITLE
Failed to remount PVC

### ISSUE THREAD

**Issue by cjyar** [openebs/mayastor#1351]
**Describe the bug**
After reboot, a PVC is failing to remount. The StorageClass has a replication factor of 2. Describing the affected Pod says:
```
  Warning  FailedMount  89s (x11 over 7m45s)  kubelet  MountVolume.MountDevice failed for volume "pvc-921d5046-6606-4415-8306-69694297dc99" : rpc error: code = Internal desc = Failed to stage volume 921d5046-6606-4415-8306-69694297dc99: attach failed: IO error:
```
There are no Kubernetes events on the PVC or PV.

**To Reproduce**
Uncertain. This happened after one of the nodes performed an unscheduled reboot.

**Expected behavior**
- PVCs should automatically mount.
- Failures should include useful diagnostic messages as events on either the Pod, PVC, or PV.

**Screenshots**
openebs-agent-ha-node logs for the affected node contain many instances of this:
```
  2023-04-10T14:49:50.946070Z  WARN agent_ha_node::path_provider: NVMe path not in cache, skipping removal, path: "/sys/devices/virtual/nvme-fabrics/ctl/nvme0"
    at control-plane/agents/src/bin/ha/node/path_provider.rs:225
```

openebs-csi-node logs for the affected node contain many instances of this:
```
  2023-04-10T15:01:04.815946Z ERROR csi_node::node: Failed to stage volume 921d5046-6606-4415-8306-69694297dc99: attach failed: IO error:
    at control-plane/csi-driver/src/bin/node/node.rs:547
```

dmesg on the affected node contains this:
```
node03: kern:     err: [2023-04-10T15:01:04.116460215Z]: nvme nvme0: Connect Invalid Data Parameter, subsysnqn "nqn.2019-05.io.openebs:921d5046-6606-4415-8306-69694297dc99"
 SUBSYSTEM=nvme
 DEVICE=c244:0
node03: kern:     err: [2023-04-10T15:01:04.118357215Z]: nvme nvme0: failed to connect queue: 0 ret=386
 SUBSYSTEM=nvme
 DEVICE=c244:0
node03: kern:     err: [2023-04-10T15:03:06.179027215Z]: nvme nvme0: Connect Invalid Data Parameter, subsysnqn "nqn.2019-05.io.openebs:921d5046-6606-4415-8306-69694297dc99"
 SUBSYSTEM=nvme
 DEVICE=c244:0
node03: kern:     err: [2023-04-10T15:03:06.180963215Z]: nvme nvme0: failed to connect queue: 0 ret=386
 SUBSYSTEM=nvme
 DEVICE=c244:0
```

** OS info (please complete the following information):**
 - Distro: Talos
 - Kernel version: `node03: kern:  notice: [2023-04-10T14:48:13.747357947Z]: Linux version 5.15.85-talos (@buildkitsandbox) (gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.39) #1 SMP Tue Dec 27 09:09:27 UTC 2022`
 - MayaStor revision or container image: v2.0.1

**Comment by tiagolobocastro** [comment]
Hey @cjyar, sorry I missed this.. which node got rebooted, application or storage?
Also could you please take a support bundle? - https://mayastor.gitbook.io/introduction/advanced-operations/supportability
Thanks!

**Comment by cjyar** [comment]
@tiagolobocastro sorry, I've moved on. I removed mayastor from this cluster and switched to jiva. It seems like it would be really challenging to re-install mayastor now without breaking things.

**Comment by adamcharnock** [comment]
In my case this was caused because I was running inconsistent Maystor versions across nodes. Two nodes had `2.6.1`, while the erroneous node had `2.7.0`. Hopefully that helps someone.

This – like the OP – happened during an unscheduled reboot. The `openebs-io-engine` DaemonSet had a pending update that hadn't been rolled out (as it is configured to non auto-rollout updates). The pod was recreated on restart, which upgraded to the pod to `2.7.0` for the restarted node.

**Comment by tiagolobocastro** [comment]
So you're saying this pending update caused the PVC to not get mounted?
And after the update then it got mounted?
