### ISSUE TITLE
Is it possible to upgrade from cStor to Mayastor seamlessly?

### ISSUE THREAD

**Issue by kvzn** [openebs/mayastor#1354]
Mayastor so efficient compared to cStor that I can't wait to put it in production environment, can anyone tell me if Mayastor v2 is mature enough for production? And if it's possible upgrade(switch) to Mayastor from cStor? Appreciate it!

**Comment by Abhinandan-Purkait** [comment]
Hi @kvzn, We have customers who are running `Mayastor` in production.

Coming to the second question, there is no upgrade path from `cStor` to `Mayastor` as both are completely different engines with different tech stacks.

**Comment by kvzn** [comment]
@Abhinandan-Purkait Got it, thank you!

**Comment by Abhinandan-Purkait** [comment]
@kvzn Closing this PR, as this doesn't have any action items. Please feel free to reopen this in case you have any further queries or concerns. 

Thank you for considering MayaStor.
