### ISSUE TITLE
Using a block device for a disk pool makes disk lost its UUID

### ISSUE THREAD

**Issue by yh0xa55a8** [openebs/mayastor#1387]
**Describe the bug**
After configure a disk into a disk pool, it's uuid lost and the disk pool cannot work properly after any reboot.

**To Reproduce**
- Installing mayastor with official helm chart.
- Configure a block device disk pool from a local disk.
- After disk pool becoming online, the disk's uuid cannot be get from `blkid` command, then, if rebooted, the `/dev/disk/by-uuid` link will lost, and the disk pool will get into "Unknown" state.

**Expected behavior**
Mayastor normally work.

** OS info (please complete the following information): **
 - Distro: Ubuntu
 - Kernel version: 5.19.0-41-generic
 - MayaStor revision: 2.1.0
 - Kubenetes Version: 1.27 deployed by microk8s.

**Additional context**
```
# output from blkid before adding disk pool
/dev/nvme0n1p1: UUID="75238d2d-e142-471d-9aba-fb4a1c15f912" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="a5d18286-a76f-dc4a-90e5-1bd540a6f738"

# output from blkid after adding disk pool
/dev/nvme0n1p1: PARTUUID="a5d18286-a76f-dc4a-90e5-1bd540a6f738"
```

my disk pool configuration
```yaml
apiVersion: openebs.io/v1alpha1
kind: DiskPool
metadata:
  creationTimestamp: "2023-05-22T11:52:40Z"
  finalizers:
  - openebs.io/diskpool-protection
  generation: 1
  name: pool-home-nvme-256
  namespace: mayastor
  resourceVersion: "1732405"
  uid: e718f864-1b08-4e4e-af3e-a76749afd1a7
spec:
  disks:
  - aio:////dev/disk/by-uuid/75238d2d-e142-471d-9aba-fb4a1c15f912
  node: home
status:
  available: 0
  capacity: 0
  cr_state: Creating
  state: Unknown
  used: 0
```

**Comment by yh0xa55a8** [comment]
And then I delete the diskpool, formatted the disk and retry:
```
# sudo blkid
/dev/nvme1n1p2: UUID="0aa86489-7526-4971-b180-b7435700e857" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="f26f003f-90e0-4217-99b6-0e009b40f313"
/dev/nvme1n1p1: UUID="C5C0-5AD4" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="3c1e9d36-4c2b-4138-9f17-53e56d45becc"
/dev/nvme0n1p1: UUID="fd1351df-2580-4281-b1b4-6f4c44312523" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="a5d18286-a76f-dc4a-90e5-1bd540a6f738"
# vim disk.yaml
# kubectl apply -f disk.yaml
diskpool.openebs.io/pool-home-nvme-256 created
# sudo blkid
/dev/nvme1n1p2: UUID="0aa86489-7526-4971-b180-b7435700e857" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="f26f003f-90e0-4217-99b6-0e009b40f313"
/dev/nvme1n1p1: UUID="C5C0-5AD4" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="3c1e9d36-4c2b-4138-9f17-53e56d45becc"
/dev/nvme0n1p1: PARTUUID="a5d18286-a76f-dc4a-90e5-1bd540a6f738"

```
The disk immediately lost it's uuid.

and io-engine logs seems normal:
```
[2023-05-22T12:47:41.847141705+00:00  INFO io_engine::grpc::v1::pool:pool.rs:163] CreatePoolRequest { name: "pool-home-nvme-256", uuid: None, disks: ["aio:////dev/disk/by-uuid/fd1351df-2580-4281-b1b4-6f4c44312523"], pooltype: Lvs }
[2023-05-22T12:47:41.847186048+00:00  INFO io_engine::lvs::lvs_store:lvs_store.rs:417] Creating or importing lvs 'pool-home-nvme-256' from 'aio:////dev/disk/by-uuid/fd1351df-2580-4281-b1b4-6f4c44312523'...
[2023-05-22T12:47:41.847749402+00:00 ERROR io_engine::lvs::lvs_store:lvs_store.rs:285] error=failed to import pool pool-home-nvme-256
[2023-05-22T12:47:42.088809112+00:00  INFO io_engine::lvs::lvs_store:lvs_store.rs:402] Lvs 'pool-home-nvme-256' [//dev/disk/by-uuid/fd1351df-2580-4281-b1b4-6f4c44312523] (232.65 GiB/232.65 GiB): new lvs created successfully
```

**Comment by tiagolobocastro** [comment]
@yh0xa55a8 seems like that uuid came from a filesystem on nvme0n1p1: TYPE="ext4" so it will indeed be removed when we setup a pool there.
Could you please remove the filesystem before creating the pool and check for a unique identifier then?

**Comment by tiagolobocastro** [comment]
Closing for now, please reopen if this is still an issue.

**Comment by nicolasbertaud** [comment]
i have exactly the same behaviour  . i have 3 node PI4 microk8s cluster.  All PI boot on SSD .
I have created a linux partition on each SSD and update fstab to mount the partition at startup .
i have enabled mayastore addon in microk8s
all pods are ok
i have created the diskpool and everything is ok
apiVersion: "openebs.io/v1alpha1"
kind: DiskPool
metadata:
  name: microk8s-pi001-poolsda3
  namespace: mayastor
spec:
  node: pi001
  disks: ["/dev/disk/by-uuid/b873b0ed-b70c-43b3-a0e8-f69e1f65b8b0"]
everything is ok untill reboot

i have deploy a nodered application using the pool
everything is ok until the reboot of a PI.

The PI don't boot and is blocked because it is unable to mount the parttion in fstab....UID for partition has dissapeared

**Comment by tiagolobocastro** [comment]
Seems like the docs were not fully update to remove by-uuid references.
if uuid comes from a previous fs it will disappear since the old fs will be gone.

**Comment by nicolasbertaud** [comment]
i follow this link https://mayastor.gitbook.io/introduction/quickstart/configure-mayastor  where is the documentation to follow to add a diskpool ?

**Comment by tiagolobocastro** [comment]
The example on that page has the command to create the diskpool:
> cat <<EOF | kubectl create -f -
apiVersion: "openebs.io/v1beta1"
kind: DiskPool
metadata:
  name: pool-on-node-1
  namespace: mayastor
spec:
  node: workernode-1-hostname
  disks: ["/dev/disk/by-id/<id>"]
EOF
