### ISSUE TITLE
[Doc Source]: [create a mayastor docker image]

### ISSUE THREAD

**Issue by light86** [openebs/mayastor#1453]
I want to create a docker image through the Mayastor source code. According to the prompts in the build.md, the correct docker image cannot be generated. How can I create my own Mayastor docker image?

**Comment by tiagolobocastro** [comment]
Hey, we might have to update the docs. I'll have a look into this during the week.
Until then, you may try something this:
`./scripts/release.sh --registry localhost:5000 --image "mayastor-io-engine" --alias-tag test-tag`

**Comment by light86** [comment]
@tiagolobocastro Thank you. Looking forward to the new docs.

**Comment by tiagolobocastro** [comment]
@light86 does the new doc changes help?

**Comment by light86** [comment]
@tiagolobocastro Yes. It works.Thank you.

I have another problem when I building io-engine manually by the doc https://github.com/openebs/spdk-rs/tree/a457fb208bebd0b18990d34b01e32e7c6f2e6ebf

Prerequisite:
mayastor branch: release/2.1
spdk branch: v22.05.x-mayastor

spdk has been built successfully.

The build errors:

[nix-shell:/data00/mayastor]# cargo build -r
.................
  = note: /nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: /data00/mayastor/target/release/libspdk-bundle.so: undefined reference to `io_uring_queue_init'
          /nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: /data00/mayastor/target/release/libspdk-bundle.so: undefined reference to `__io_uring_get_cqe'
          /nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: /data00/mayastor/target/release/libspdk-bundle.so: undefined reference to `io_uring_queue_exit'
          /nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: /data00/mayastor/target/release/libspdk-bundle.so: undefined reference to `io_uring_submit'
          collect2: error: ld returned 1 exit status
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
.................

**Comment by tiagolobocastro** [comment]
hmm did you checkout the correct spdk branch?
Maybe @dsavitskiy can help here

**Comment by light86** [comment]
@tiagolobocastro @dsavitskiy 
I checkout the branch origin/v22.05.x-mayastor. 
And execute build_spdk.sh under dir spdk-rs to build spdk, it's sucesssful. 

I build mayastor by two ways:
one is 'nix-shell --args nospdk true', failed.
another is 'nix-shell', successful.
I find a difference for libspdk-bundle.so, in the way of 'nix-shell --args nospdk' libspdk-bundle.so did't link to liburing.so.2. As shown below.

nix-shell:
[nix-shell:/data00/mayastor]# ldd target/debug/libspdk-bundle.so
	linux-vdso.so.1 (0x00007ffe8b5d8000)
	libaio.so.1 => /nix/store/av6fxyh7vjgcp613zrpbmia9i0isy2zq-libaio-0.3.113/lib/libaio.so.1 (0x00007f7d60825000)
	libbsd.so.0 => /nix/store/swjjj51mzg8z0yncqv5hp9v29gkkkvmx-libbsd-0.11.6/lib/libbsd.so.0 (0x00007f7d6080e000)
	libcrypto.so.3 => /nix/store/4mxnw95jcm5a27qk60z7yc0gvxp42b9a-openssl-3.0.7/lib/libcrypto.so.3 (0x00007f7d6038d000)
	libdl.so.2 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libdl.so.2 (0x00007f7d60388000)
	libm.so.6 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libm.so.6 (0x00007f7d602a8000)
	libnuma.so.1 => /nix/store/664hlv5rfi4j1z1sa6jzj49sg7l2k03m-numactl-2.0.16/lib/libnuma.so.1 (0x00007f7d6029a000)
	libpcap.so.1 => /nix/store/cdrs17s1dbdzv0giqvm2lzvxkwrwl6k2-libpcap-1.10.1/lib/libpcap.so.1 (0x00007f7d60250000)
	librt.so.1 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/librt.so.1 (0x00007f7d6024b000)
	**liburing.so.2 => /nix/store/bqx02nb4iyrv5mldzryrn58995xhl9dj-liburing-2.2/lib/liburing.so.2 (0x00007f7d60242000)**
	libuuid.so.1 => /nix/store/f8v8m9pzg3zv9yq970fc9f5nki8k9x32-util-linux-2.38.1-lib/lib/libuuid.so.1 (0x00007f7d60239000)
	libmd.so.0 => /nix/store/b1gz2zv1yrjzkmcwp6pjghkn7n9myry6-libmd-1.0.4/lib/libmd.so.0 (0x00007f7d6022c000)
	libssl.so.3 => /nix/store/4mxnw95jcm5a27qk60z7yc0gvxp42b9a-openssl-3.0.7/lib/libssl.so.3 (0x00007f7d6017f000)
	libc.so.6 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libc.so.6 (0x00007f7d5ff76000)
	/nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib64/ld-linux-x86-64.so.2 (0x00007f7d644c2000)
	libpthread.so.0 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libpthread.so.0 (0x00007f7d5ff6f000)

nix-shell --args nospdk true:
[nix-shell:/data00/mayastor]# ldd target/release/libspdk-bundle.so
	linux-vdso.so.1 (0x00007ffee6ebe000)
	libaio.so.1 => /nix/store/av6fxyh7vjgcp613zrpbmia9i0isy2zq-libaio-0.3.113/lib/libaio.so.1 (0x00007efd0cf8f000)
	libbsd.so.0 => /nix/store/swjjj51mzg8z0yncqv5hp9v29gkkkvmx-libbsd-0.11.6/lib/libbsd.so.0 (0x00007efd0cf78000)
	libcrypto.so.3 => /nix/store/4mxnw95jcm5a27qk60z7yc0gvxp42b9a-openssl-3.0.7/lib/libcrypto.so.3 (0x00007efd0caf7000)
	libdl.so.2 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libdl.so.2 (0x00007efd0caf2000)
	libm.so.6 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libm.so.6 (0x00007efd0ca12000)
	libnuma.so.1 => /nix/store/664hlv5rfi4j1z1sa6jzj49sg7l2k03m-numactl-2.0.16/lib/libnuma.so.1 (0x00007efd0ca04000)
	libpcap.so.1 => /nix/store/cdrs17s1dbdzv0giqvm2lzvxkwrwl6k2-libpcap-1.10.1/lib/libpcap.so.1 (0x00007efd0c9ba000)
	librt.so.1 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/librt.so.1 (0x00007efd0c9b5000)
	libuuid.so.1 => /nix/store/f8v8m9pzg3zv9yq970fc9f5nki8k9x32-util-linux-2.38.1-lib/lib/libuuid.so.1 (0x00007efd0c9aa000)
	libmd.so.0 => /nix/store/b1gz2zv1yrjzkmcwp6pjghkn7n9myry6-libmd-1.0.4/lib/libmd.so.0 (0x00007efd0c99d000)
	libssl.so.3 => /nix/store/4mxnw95jcm5a27qk60z7yc0gvxp42b9a-openssl-3.0.7/lib/libssl.so.3 (0x00007efd0c8f0000)
	libc.so.6 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libc.so.6 (0x00007efd0c6e7000)
	/nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib64/ld-linux-x86-64.so.2 (0x00007efd10c3e000)
	libpthread.so.0 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libpthread.so.0 (0x00007efd0c6e2000)

Where should I configure it to link to this library?

**Comment by tiagolobocastro** [comment]
Branch should be this hash https://github.com/openebs/mayastor/blob/9968d94f948a187c6c09c0a0e21ab6ce34a0b917/nix/pkgs/libspdk/default.nix#L64: so v23.01.x-mayastor
