### ISSUE TITLE
Official docs and this repository still indicate that this is a beta product

### ISSUE THREAD

**Issue by nzbart** [openebs/mayastor#1467]
I almost disregarded Mayastor because of this statement on your documentation page:

>Mayastor is beta software and is under active development

Source: https://openebs.io/docs/concepts/mayastor

However, since the product is now 2.x, and as confirmed in the following issue, my understanding is that Mayastor is ready for production use:

https://github.com/openebs/mayastor/issues/1130

To avoid putting potential users off, would pay to update the following documentation:
* https://openebs.io/docs/concepts/mayastor
* https://github.com/openebs/mayastor/blob/06f7edbb459595328c365a813317415b43d33453/CONTRIBUTING.md

**Comment by avishnu** [comment]
Thanks for reporting this. It has been addressed as a part of this [PR](https://github.com/openebs/mayastor/pull/1470).

**Comment by avishnu** [comment]
Ok, I now see that there are couple of other places as well that you have pointed out in your PR description. Sorry about that.
Re-opening !!!

**Comment by tiagolobocastro** [comment]
@avishnu why was this reopened, something still left to fix?
EDIT: I see, a PR exists in the website repo for this...
https://github.com/openebs/website/pull/376

**Comment by tiagolobocastro** [comment]
I think it's all done now, please reopen if otherwise.
