### ISSUE TITLE
build.md: after git clone and before releash.sh a "git submodule update --init --recursive" is needed

### ISSUE THREAD

**Issue by bhuism** [openebs/mayastor#1483]
when following the mayastor build instructions per build.md

there is no mention of:

git submodule update --init --recursive

(no git clone either, don't know if that is a good thing btw)

please update docs, add:

git submodule update --init --recursive

**Comment by tiagolobocastro** [comment]
Yeah seems like we don't, would you like to open a PR for this? :)

**Comment by bhuism** [comment]
@tiagolobocastro done
