### ISSUE TITLE
compile error in io-engine/src/bdev/malloc.rs:172:23

### ISSUE THREAD

**Issue by bhuism** [openebs/mayastor#1484]
When build vanilla v2.3 (on arm(!)) I got:

Compiling crossbeam-sync v0.0.0
error[E0308]: mismatched types
   --> io-engine/src/bdev/malloc.rs:172:23
    |
172 |                 name: cname.as_ptr() as *mut i8,
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`

Which I fixed with: https://github.com/bhuism/mayastor/commit/fc330d50035e40346e3490741d4f7aa654bacb8b

d'you want a pr for this on development? ( I forked v2.3 )

(after this io-engine build was 100% fine btw)

**Comment by tiagolobocastro** [comment]
Hey, a PR for develop would be great as we'll be branching 2.4 out of develop in a not too distant future :)

**Comment by bhuism** [comment]
@tiagolobocastro done
