### ISSUE TITLE
Mayastor Storage Dependent Storage

### ISSUE THREAD

**Issue by weironz** [openebs/mayastor#1488]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

why mayastor Storage Dependent other Storage? This is too strange. If I have storage, why would I use mayastor.

- loki-stack.persistence.storageClassName: manual
- etcd.persistence.storageClassName: manual

**Describe alternatives you've considered**

**Additional context**

**Comment by weironz** [comment]
```
--set loki-stack.loki.persistence.storageClassName=manual
--set etcd.persistence.storageClass=manual
```

**Comment by tiagolobocastro** [comment]
I've raised a PR to fix this: https://github.com/openebs/mayastor-docs/pull/159
