### ISSUE TITLE
Multiple pools and dedicated storageClasses for different storage use cases (fast, slow, ...)

### ISSUE THREAD

**Issue by urbaman** [openebs/mayastor#1517]
**Is your feature request related to a problem? Please describe.**

Ablity to define the storageClass to a specific pool, to easily define slow/fast storage definitions

**Describe the solution you'd like**

Probaly setting the storageClass wit a tag also presnet on the targeted pools

**Describe alternatives you've considered**

I'm actually using longhorn, in which it's safe defining and tagging different pools and then targeting them with different storageClasses

**Additional context**

See how longhorn uses both nodeSelector and diskSelector in the storageClass definition

**Comment by tiagolobocastro** [comment]
Hi @urbaman, this is actually current being planned and designed for a coming release :)

**Comment by tiagolobocastro** [comment]
#1545 will be updated once work is complete, please reopen if the approach discussed there doesn't fit your needs. Thanks
