### ISSUE TITLE
[Doc Source]: [Disk preparation]

### ISSUE THREAD

**Issue by urbaman** [openebs/mayastor#1530]
**Are you reporting an issue with existing content?**
The documentation reports it needs unpartitioned, unformatted disks, and asks for uuid.
So, how to properly get a working unpartitioned and unformatted disk, with uuid?
Should I go with pv, vg and lv, giving the lv to mayastor? Should I stop at the pv?

**Are you proposing new content, or a change to the existing documentation layout or structure?**
Please describe the best and preferred method to prepare a disk for Mayastor.

**Comment by tiagolobocastro** [comment]
@urbaman we need to fix docs to say by-path or by-id
The intent was for users to provide a path which did not change across boots.

**Comment by tiagolobocastro** [comment]
Docs are updated
