### ISSUE TITLE
mayastor upgrade container architecture

### ISSUE THREAD

**Issue by bhuism** [openebs/mayastor#1533]
Is there a way to specify the architecture on the upgrade container when:

```mayastor upgrade```

is given?

or is it always amd64?

(I am happily running mayastor on arm 👍)

**Comment by tiagolobocastro** [comment]
hmm current helm chart sets up amd64 images, how did you specify the arm images? Did you tweak the helm to point to your registry or did you modify the daemonset directly?

**Comment by bhuism** [comment]
I've build all the containers (which went really well btw)

https://github.com/bhuism/home-ops/blob/main/charts/root/templates/mayastor/app.yaml

I've pointed the helm chart to my registry, but the upgrade command seems to always get the amd64 'upgrade' container

**Comment by tiagolobocastro** [comment]
Ah I see... So it pulls from docker.io registry rather than your own?

**Comment by bhuism** [comment]
Yes, and the wrong (amd64) architecture

(if you guys would be able to build arm images that would be awesome, it build perfectly fine, without any support off source)

**Comment by tiagolobocastro** [comment]
@niladrih from what I can see upgrade should get the "correct" registry from running config, any ideas what could be the issue here?

> (if you guys would be able to build arm images that would be awesome, it build perfectly fine, without any support off source)

The main reason for this has been because we don't run any tests on arm (or even built it) so we can't guarantee it'll work :(

**Comment by bhuism** [comment]
Where/how can I double check the docker registry url value from the 'running config'?  where is it stored?

also, can you check that the "correct" architecture is pulled?

**Comment by niladrih** [comment]
> @niladrih from what I can see upgrade should get the "correct" registry from running config, any ideas what could be the issue here?
> 
> > (if you guys would be able to build arm images that would be awesome, it build perfectly fine, without any support off source)
> 
> The main reason for this has been because we don't run any tests on arm (or even built it) so we can't guarantee it'll work :( 

Oh, it does. It'd use whatever registry is currently serving the REST container image (source installation).

I'd assume two separate things are at play here:
1. Using a pre-built `kubectl mayastor` binary -- you'd have to build the kubectl mayastor with the same git tag as the upgrade-job container image tag

2. Using the same source (initial) container registry on the source installation of the helm chart as the custom built upgrade job image -- the upgrade-job container is pulled from where the source chart's REST API container is pulled. I can see how a new option to input the registry could help here :)

**Comment by bhuism** [comment]
hmmm,

```kubectl -n mayastor describe jobs.batch mayastor-upgrade-v2-4-0``` gives:

```
...
  Containers:
   mayastor-upgrade-job:
    Image:      docker.io/openebs/mayastor-upgrade-job:v2.4.0
...
```

so it's not using my custom container registry.

how can I check the 'config' of mayastor where the registry url is confogured, I've put:

```
        image:
          registry: europe-west4-docker.pkg.dev/impl-383520/docker
```

in the helm chart (and mayastor runs fine)

**Comment by niladrih** [comment]
@bhuism  -- the mayastor images for the chart which is installed (pre-upgrade) need to be from `europe-west4-docker.pkg.dev`. That is the registry that the `kubectl mayastor upgrade` will use for the openebs/mayastor-upgrade-job container.

You can check your configuration with this command `helm get values <helm-release-name> -n <namespace> -a -o yaml`.

**Comment by bhuism** [comment]
When I run:
```helm template mayastor/mayastor -f values.yaml | grep "image:"```

I get:

```          image: busybox:latest
        image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-agent-ha-node:v2.4"
        image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-csi-node:v2.4"
        image: "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0"
          image: busybox:latest
          image: busybox:latest
        image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-metrics-exporter-pool:v2.4"
        image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-io-engine:v2.4"
        image: "openebs/provisioner-localpv:3.4.0"
          image: busybox:latest
          image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-agent-core:v2.4"
          image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-agent-ha-cluster:v2.4"
          image: busybox:latest
          image: busybox:latest
          image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-api-rest:v2.4"
          image: busybox:latest
          image: "registry.k8s.io/sig-storage/csi-provisioner:v3.5.0"
          image: "registry.k8s.io/sig-storage/csi-attacher:v4.3.0"
          image: "registry.k8s.io/sig-storage/csi-snapshotter:v6.2.1"
          image: "registry.k8s.io/sig-storage/snapshot-controller:v6.2.1"
          image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-csi-controller:v2.4"
          image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-obs-callhome:v2.4"
          image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-obs-callhome-stats:v2.4"
          image: busybox:latest
          image: busybox:latest
          image: "europe-west4-docker.pkg.dev/impl-383520/docker/openebs/mayastor-operator-diskpool:v2.4"
          image: docker.io/bitnami/os-shell:11
          image: docker.io/bitnami/etcd:3.5
        image: nats:2.9.17-alpine
        image: natsio/nats-server-config-reloader:0.10.1
        image: natsio/prometheus-nats-exporter:0.11.0
    image: natsio/nats-box:0.13.8
```

looks ok right?

and values.yaml contains:

```        image:
          registry: europe-west4-docker.pkg.dev/impl-383520/docker
          repo: openebs
          tag: v2.4
        obs:
          ​callhome:
            ​enabled: false            
        nodeSelector:
            kubernetes.io/arch: arm64
        io_engine:
          nodeSelector:
            kubernetes.io/arch: arm64
            openebs.io/engine: mayastor
            mayastorage.impl.nl: "true"
          resources:
            limits:
              cpu: "900m"
            requests:
            requests:
              cpu: "900m"
        loki-stack:
          enabled: false
          loki-stack:
            ​enabled: false
            ​loki:
              enabled: false
              persistence:
                ​enabled: false
            promtail:
              enabled: false
        etcd:
          replicaCount: 3
          image:
            tag: 3.5
          persistence:
            enabled: true
            size: 1Gi
          volumePermissions:
            image:
              repository: bitnami/os-shell
              tag: 11
```

when I run:

```kubectl mayastor upgrade```

I get manifests which the wrong repo url:

the pod:

```
bhuism@elza:~$ kubectl -n mayastor get Job -o yaml | grep image:
          image: docker.io/openebs/mayastor-upgrade-job:v2.4.0
```
and the job:
```
bhuism@elza:~$ kubectl -n mayastor get pod/mayastor-upgrade-v2-4-0-vlhrt -o yaml | grep image:
    image: docker.io/openebs/mayastor-upgrade-job:v2.4.0
  - image: docker.io/openebs/mayastor-upgrade-job:v2.4.0
```

My question is, how can I override the image url for the upgrade manfests?

**Comment by bhuism** [comment]
@niladrih How would one go about changing the architecture of the upgrade container if one wants?

**Comment by niladrih** [comment]
@bhuism -- makes sense for there to be an option to specify the registry for the upgrade container image. I'll try to push this change in.

**Comment by niladrih** [comment]
@bhuism -- I see this change going in into the 2.5.0 release...

**Comment by bhuism** [comment]
Many thanks, is the architecture correct? Am a bit afraid that the wrong architecture image will be pulled, i can this this obviously

**Comment by niladrih** [comment]
@bhuism -- I don't have an arm64 system at hand at the moment. If you use an arm64 image, the rest of it should fall into place. There is no specific Kubernetes Job yaml parameter which specifies the arch, I think.

Here's how you can test if this change will work for you, if and when it is released with 2.5.0:
1. Pull in the recent changes to the openebs/mayastor-extensions repo in the develop branch. Update the git submodules...
```
./scripts/nix/git-submodule-init.sh --force
```
1. Choose a tag you'd like to test with, which is higher than the installed version. E.g. `v2.5.0-bhuism`
2. Build your arm64 upgrade-job image with the tag, and push it to your image registry.
3. Build the kubectl-mayastor binary with the same tag
```
# Assuming linux..
nix-build --out-link ./kubectl-mayastor -A utils.release.linux-musl.kubectl-plugin --argstr tag v2.5.0-bhuism
```
4. Try to upgrade with the kubectl-mayastor binary
```
./kubectl-mayastor/bin/kubectl-mayastor upgrade --registry <your-registry> --allow-unstable
```
5. Check to see if the upgrade-job container gets pulled..

**Comment by bhuism** [comment]
Will do, thanks for the update, I saw amd64 (not arm64) being pulled in 2.4.0, so I thought, just repo url is maybe not enough, I'll test, thanks again

**Comment by niladrih** [comment]
Sure. I'd love to know if it worked for you, or if there's something that we're still missing...

**Comment by bhuism** [comment]
Im working on it
