### ISSUE TITLE
How to build the binary Mayastor without NixOS

### ISSUE THREAD

**Issue by MengjinWu** [openebs/mayastor#1547]
I am trying to build the io-engine-client and mayastor binary.
But I tried with the instruction in run.md:

I do not have NixOS and using following scripts and got the error output:
```
❯ nix-shell -I nixpkgs=channel:nixpkgs-unstable -p nixUnstable --command "nix --experimental-features 'nix-command flakes' shell -f . mayastor"

error: attribute 'mayastor' in selection path 'mayastor' not found
```

What should I do to build the mayastor binary?
And how can I build the io-engine-client binary?

Thanks.

**Comment by tiagolobocastro** [comment]
I'm not too familiar with flakes, so I'll suggest you use the older nix commands.
(Perhaps we should remove flakes from the docs as well..)

Anyway, if you just want the binaries readily available:
```
$> nix-build -A io-engine-dev # io-engine for release binaries, and io-engine-dev for debug
....
/nix/store/rsrh51gnv049jjpak0izg3bzygwmk7x4-io-engine
$> ls /nix/store/rsrh51gnv049jjpak0izg3bzygwmk7x4-io-engine/bin
casperf  initiator  io-engine  io-engine-client  jsonrpc  nvmet  spdk  uring-support
```

If you want to make changes and test I suggest using the nix-shell, example:
`nix-shell ci.nix`
And then just use rust/cargo workflow, example, cargo build --bins...

**Comment by tiagolobocastro** [comment]
@MengjinWu did that work for you? If it did I think we'll go ahead and update docs to remove flakes and become simpler

**Comment by MengjinWu** [comment]
Yes it can work, Thanks!
Does control-plane have this same method?

**Comment by tiagolobocastro** [comment]
Indeed it does, but there are various components there.
You can actually use the `./scripts/release.sh --help` which should exist on all mayastor repos and will build and even push the images btw.

**Comment by orville-wright** [comment]
@MengjinWu Do you consider this issue resolved? So we can close it out?

**Comment by MengjinWu** [comment]
Thanks!
