### ISSUE TITLE
[chart]: skip Jaeger CRD if Jaeger tracing is disabled

### ISSUE THREAD

**Issue by cmontemuino** [openebs/mayastor#1586]
**Describe the bug**
Jaeger tracing is a conditional dependency: https://github.com/openebs/mayastor-extensions/blob/v2.5.0/chart/Chart.yaml#L34

It is disabled by default: https://github.com/openebs/mayastor-extensions/blob/v2.5.0/chart/values.yaml#L94

Thus, its CRD should not be installed: https://github.com/openebs/mayastor-extensions/blob/v2.5.0/chart/crds/jaeger.yaml

The general use case here is having Jaeger installed outside OpenEBS Mayastor chart.

**To Reproduce**

`helm install` will output the CRD, even if jaeger is not enabled

**Expected behavior**

Jaeger CRDs should not be installed unless enabled

**Screenshots**

N.A.

** OS info (please complete the following information):**
 - Distro: [e.g. NixOS]: NA
 - Kernel version: NA
 - MayaStor revision or container image: chart release v2.5.0

**Additional context**
NA

**Comment by cmontemuino** [comment]
I'm keen to open a PR with a fix

**Comment by tiagolobocastro** [comment]
Sounds good @cmontemuino, we'll be happy to take a fix for this :)

**Comment by cmontemuino** [comment]
Hi @tiagolobocastro, the PR is larger than expected: https://github.com/openebs/mayastor-extensions/pull/414

- It addresses the typical issues with CRDs in Helm 3

There's a lint task failing, but I can't realize if it's me or some misconfiguration in the github actions: https://github.com/openebs/mayastor-extensions/actions/runs/7797125901/job/21263134039?pr=414

**Comment by tiagolobocastro** [comment]
PR was merged, let's close this now.
Also Jaeger CRD is no longer included.
