### ISSUE TITLE
Build Mayastor Kubectl Plugin for different platforms and architectures

### ISSUE THREAD

**Issue by sherif-fanous** [openebs/mayastor#1606]
**Is your feature request related to a problem? Please describe.**

The Mayastor Kubectl plugin is only available as an x86_x64 binary thus cannot be installed on any Apple computer (Either Intel or Apple Silicon) which happen to be my daily driver

While I understand that building and testing ARM64 images for Mayastor itself would be a large endeavor I'm hoping that making the plugin available for other platforms/architectures (e.g. ARM64, Apple x86_x64 and Apple Silicon) would be just a matter of cross compiling the binary.

**Describe the solution you'd like**
Build the Mayastor Kubectl Plugin for other platforms and architectures

**Describe alternatives you've considered**
Install the plugin in a Docker container

**Comment by tiagolobocastro** [comment]
We cross-compile to arm64 atm, but IIRC we had issues cross compiling from darwin x86_64 to darwin arm64.
I'll see what the state of things is atm..
You can still run the x86_64 binary on arm64 darwin using rosetta though!

**Comment by tiagolobocastro** [comment]
Alright, seems we now have aarch64 darwin runners!
https://github.com/openebs/mayastor-extensions/pull/442
Could you please try this binary: https://github.com/openebs/mayastor-extensions/actions/runs/8289637439/artifacts/1328050608

**Comment by sherif-fanous** [comment]
Works!!!

Thanks @tiagolobocastro

**Comment by tiagolobocastro** [comment]
Alright, it's merged and show be available for 2.6 :)
