### ISSUE TITLE
Luks / CryptSetup / Encryption device overwriten

### ISSUE THREAD

**Issue by todeb** [openebs/mayastor#1627]
**Describe the bug**
Luks created devices are overwrtten.

**To Reproduce**
```
cryptsetup --verbose --verify-passphrase luksFormat /dev/sdc1
cryptsetup -open /dev/sdc1 sdc1

./kubectl-mayastor get block-devices node --all
 /dev/sdc1     partition  6GiB     ... "/dev/disk/by-uuid/06543852-22b2-4f4f-8461-fc5d6a7cac5b"

-- create diskpool

apiVersion: "openebs.io/v1beta1"
kind: DiskPool
metadata:
  name: pool1-on-node
  namespace: mayastor
spec:
  disks:
  - /dev/disk/by-uuid/06543852-22b2-4f4f-8461-fc5d6a7cac5b
  node: node
                              

then:
cryptsetup close sdc1

cryptsetup luksOpen /dev/sdc1 sdc1
Device /dev/sdc1 is not a valid LUKS device.
   
```

**Expected behavior**
disk pool created  on luks encrypted device

**Screenshots**

** OS info (please complete the following information):**
 - Distro: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-101-generic x86_64)
 - Kernel version
 - MayaStor revision or container image: 2.50

**Additional context**

from doc: https://openebs.io/docs/faqs/general#encryption-rest
```
OpenEBS team is working on introducing native encryption capabilities with the release of the Mayastor storage engine.
```
Doc does not specifically say that LUKS is not supported on Maya, but says it is generally recommended for openebs.

**Comment by tiagolobocastro** [comment]
Hi @todeb, is /dev/disk/by-uuid/06543852-22b2-4f4f-8461-fc5d6a7cac5b" pointing to the crypt device or is it pointing to the raw disk? If it's pointing to the raw disk then yes I image the encryption device would be overwritten.

**Comment by todeb** [comment]
ok, got it. there is new device /dev/dm-0 listed by kube-mayastor, didn't notice it before. My bad. Thanks.

**Comment by tiagolobocastro** [comment]
Cool no worries. Btw we've recently changed our docs to advise ppl to use by-id or by-partid (for partitions) rather than by-uuid as it seems by-uuid is used mostly by filesystems so when we create a pool it also erases the filesystem and thefore erases the by-uuid dev link.
