### ISSUE TITLE
Data not available without parent nexus.

### ISSUE THREAD

**Issue by ankit16-19** [openebs/mayastor#1636]
Hi, team. Great work with mayastor.

I need some help to understand a few things. It seems like docs are not up to date https://github.com/openebs/mayastor/blob/develop/doc/mayastor-client.md

Context:
I am trying to setup mayastor as block replicator in linux i.e without using k8s.

I have two machines machineA(/dev/sda, /dev/sdb), machineB(/dev/sda).

MACHINE-A: 

I tried to setup two nexus on machine A like this
> fallocate -l 2GiB /data/file.img
> io-engine-client nexus create cnode1 1GiB 'aio:///data/file.img?blk_size=512'
> io-engine-client nexus create cnode2 1GiB aio:///dev/sdb

Then i publish both of them.

MACHINE-B:
I setup a nexus using
io-engine-client nexus create node12 64MiB 'nvmf://{machineA-IP}:8420/nqn.2019-05.io.openebs:cnode1' 'nvmf://{machineA-IP}:8420/nqn.2019-05.io.openebs:cnode2'

Next, I publish the nexus 'node12'
Next I mount the nexus using nvme.sudo nvme connect-all -t tcp -a 127.0.0.1 -s 8420

sudo mount /dev/nvme0n1 /mnt

It's asks me to format, then i write data onto it.
I unmount and remount to verify the data.

problem:
When I mount cnode1 and cnode2 nexus directly to the Machine2. To check if i have the data.
It doesn't show up.

What i want to achieve:
machine 1 exposes two nvmfs. cnode1, cnode2
machine 2 create nexus using the above two. writes the data.

now data should be available in individual nexuses,
even if i don't want to use parent nexus!. i.e directly mounting cnode1, cnode2

**Comment by tiagolobocastro** [comment]
Hi @ankit16-19,

I think the problem is that the nexus currently reserves 5MiB at the start of the child for metadata, so the actual data is at an offset. You could potentially add a flag to disable this offset usage.
Also if you're simply sharing cnode1 from one node, then you can just share it directly using bdev, you don't need a nexus for that.

**Comment by ankit16-19** [comment]
@tiagolobocastro when i do bdev share it also creates a nvmf link.
does sharing through bdev. and access/mount that share something different?

can you please walk me through a small example of create-sharing-mounting bdev.

**Comment by ankit16-19** [comment]
> Hi @ankit16-19,
> 
> I think the problem is that the nexus currently reserves 5MiB at the start of the child for metadata, so the actual data is at an offset. You could potentially add a flag to disable this offset usage. Also if you're simply sharing cnode1 from one node, then you can just share it directly using bdev, you don't need a nexus for that.

which flag is that?

**Comment by ankit16-19** [comment]
> Hi @ankit16-19,
> 
> I think the problem is that the nexus currently reserves 5MiB at the start of the child for metadata, so the actual data is at an offset. You could potentially add a flag to disable this offset usage. Also if you're simply sharing cnode1 from one node, then you can just share it directly using bdev, you don't need a nexus for that.

Can you please help with this
when i do bdev share it also creates a nvmf link.
does sharing through bdev. and access/mount that share something different?

can you please walk me through a small example of create-sharing-mounting bdev.

**Comment by tiagolobocastro** [comment]
> > Hi @ankit16-19,
> > I think the problem is that the nexus currently reserves 5MiB at the start of the child for metadata, so the actual data is at an offset. You could potentially add a flag to disable this offset usage. Also if you're simply sharing cnode1 from one node, then you can just share it directly using bdev, you don't need a nexus for that.
> 
> which flag is that?

I meant you'd have to have it, current doesn't exist.
I think this is the place where we calculate the offset: https://github.com/openebs/mayastor/blob/3f0aa9cd7d25ecbb22389d3156ccba7d21d6f0b8/io-engine/src/bdev/nexus/nexus_bdev.rs#L733

**Comment by tiagolobocastro** [comment]
> > Hi @ankit16-19,
> > I think the problem is that the nexus currently reserves 5MiB at the start of the child for metadata, so the actual data is at an offset. You could potentially add a flag to disable this offset usage. Also if you're simply sharing cnode1 from one node, then you can just share it directly using bdev, you don't need a nexus for that.
> 
> Can you please help with this when i do bdev share it also creates a nvmf link. does sharing through bdev. and access/mount that share something different?
> 
> can you please walk me through a small example of create-sharing-mounting bdev.

As I mentioned, the problem is the offset, you need to add a flag to remove the offsets if you want to open same data directly from the cnodes
I can try to create some branch with a small change next week if you'd like, otherwise you can give it a go first and let me know if you need any help.

Should we close this ticket for now and you can ping me directly on slack or open a discussion instead?

**Comment by ankit16-19** [comment]
yes sure, i will ping you later on slack. Thanks for the update.
