### ISSUE TITLE
Cannot delete volumesnapshotcontents

### ISSUE THREAD

**Issue by todeb** [openebs/mayastor#1664]
**Describe the bug**
kubectl delete volumesnapshotcontents .... not deleting snapshots.

Previously I had some snapshots and was able to delete it but this time cannot.
Snapshots were made by velero.

**To Reproduce**
not sure if it is reproducable, although.
* install velero, 
* do backup with velero with csisnapshots
* remove all backups from velero
* snapshotcontents leftover and cannot be deleted

**Expected behavior**
snapshotscontents are removed

**Screenshots**

** OS info (please complete the following information):**
openebs.io/version: 2.6.1

**Additional context**
I do not have much exp with snapshots. is there any log that I can check why the snapshotcontents are not removing?

```
kubectl get volumesnapshots -A
No resources found
```
I have more of these which cannot be deleted, sharing just 2:
```
kubectl get volumesnapshotcontents
NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER                    VOLUMESNAPSHOTCLASS          VOLUMESNAPSHOT                             VOLUMESNAPSHOTNAMESPACE   AGE
snapcontent-8adba276-e0f7-4174-ba68-48dce32cdcf6   true         21474836480   Delete           io.openebs.csi-mayastor   csi-mayastor-snapshotclass   velero-datadir-mongodb-primary-0-hn6h9     test                      18h
snapcontent-cb713c51-288a-44b7-9cbf-b283f466d2d3   true         21474836480   Delete           io.openebs.csi-mayastor   csi-mayastor-snapshotclass   velero-datadir-mongodb-secondary-0-8kqds   test                      18h
```

```
kubectl get volumesnapshotcontents snapcontent-cb713c51-288a-44b7-9cbf-b283f466d2d3 -o yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  creationTimestamp: "2024-05-22T14:39:12Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2024-05-22T15:23:57Z"
  finalizers:
  - snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
  generation: 2
  labels:
    velero.io/backup-name: testbackup1
  name: snapcontent-cb713c51-288a-44b7-9cbf-b283f466d2d3
  resourceVersion: "578783786"
  uid: 70edcebe-c9a4-4b4f-899d-50139ca58041
spec:
  deletionPolicy: Delete
  driver: io.openebs.csi-mayastor
  source:
    volumeHandle: a73c02e7-38dd-43fe-b7ee-37c908063175
  sourceVolumeMode: Filesystem
  volumeSnapshotClassName: csi-mayastor-snapshotclass
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: velero-datadir-mongodb-secondary-0-8kqds
    namespace: test
    resourceVersion: "577524981"
    uid: cb713c51-288a-44b7-9cbf-b283f466d2d3
status:
  creationTime: 1716388760222428717
  readyToUse: true
  restoreSize: 21474836480
  snapshotHandle: cb713c51-288a-44b7-9cbf-b283f466d2d3
```

```
kubectl describe volumesnapshotcontents/snapcontent-cb713c51-288a-44b7-9cbf-b283f466d2d3
Name:         snapcontent-cb713c51-288a-44b7-9cbf-b283f466d2d3
Namespace:
Labels:       velero.io/backup-name=testbackup1
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshotContent
Metadata:
  Creation Timestamp:             2024-05-22T14:39:12Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2024-05-22T15:23:57Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
  Generation:        2
  Resource Version:  578783786
  UID:               70edcebe-c9a4-4b4f-899d-50139ca58041
Spec:
  Deletion Policy:  Delete
  Driver:           io.openebs.csi-mayastor
  Source:
    Volume Handle:             a73c02e7-38dd-43fe-b7ee-37c908063175
  Source Volume Mode:          Filesystem
  Volume Snapshot Class Name:  csi-mayastor-snapshotclass
  Volume Snapshot Ref:
    API Version:       snapshot.storage.k8s.io/v1
    Kind:              VolumeSnapshot
    Name:              velero-datadir-mongodb-secondary-0-8kqds
    Namespace:         test
    Resource Version:  577524981
    UID:               cb713c51-288a-44b7-9cbf-b283f466d2d3
Status:
  Creation Time:    1716388760222428717
  Ready To Use:     true
  Restore Size:     21474836480
  Snapshot Handle:  cb713c51-288a-44b7-9cbf-b283f466d2d3
Events:             <none>
```
here are all of them..
```
kubectl-mayastor -n openebs get volume-snapshots
 ID                                    TIMESTAMP             SOURCE-SIZE  ALLOCATED-SIZE  TOTAL-ALLOCATED-SIZE  SOURCE-VOL                            RESTORES
 28addbac-dcd6-40e9-ab17-27880887c2e6  2024-05-22T14:39:14Z  20GiB        20MiB           9GiB                  424eb32a-7070-4333-8e81-32a59bb5238e  0
 2ba41de2-ba73-4daa-96e7-8a220d2a6e34  2024-05-22T14:39:18Z  8GiB         396MiB          396MiB                2eb5bf88-f68d-4d43-9e65-e565eca7885c  0
 2e512ead-1a7b-4088-b723-06576869402c  2024-05-22T14:39:13Z  20GiB        816MiB          816MiB                ec01a049-1156-4380-9d9f-3f2f92186191  0
 3b5b539b-1600-47b5-91f4-18f166c62a09  2024-05-22T14:39:12Z  8GiB         400MiB          400MiB                5e54965b-2fd6-4f7f-bea1-ecdd927225c9  0
 5ee36145-7b50-4c2a-8e58-b37ac424006e  2024-05-22T14:39:19Z  20GiB        24MiB           9.1GiB                bc32035b-6afb-4872-a739-127bbaf89de4  0
 675103cf-2388-4efb-a2b0-7c51e18783c7  2024-05-22T14:39:20Z  20GiB        28MiB           9GiB                  ffa9007f-02fe-44e3-ac93-c0543e0c8882  0
 765aed54-5fbd-495c-a3be-94f46bda9350  2024-05-22T14:39:13Z  20GiB        0 B             9.6GiB                6898e456-087c-481a-9b47-f4424dba7499  0
 7de92f6b-5bd3-4040-951c-8aa44f5da8df  2024-05-22T14:39:13Z  20GiB        9.1GiB          9.1GiB                bc32035b-6afb-4872-a739-127bbaf89de4  0
 852ea371-f6cc-4c6d-a90d-b9a840eaff01  2024-05-22T14:39:13Z  20GiB        8.9GiB          8.9GiB                424eb32a-7070-4333-8e81-32a59bb5238e  0
 8adba276-e0f7-4174-ba68-48dce32cdcf6  2024-05-22T14:39:19Z  20GiB        588MiB          588MiB                8a4dbcf6-a428-4227-b72b-644ffa1d5fa8  0
 8f5e1116-d602-4f18-83ff-87b809605d88  2024-05-22T14:39:13Z  20GiB        9GiB            9GiB                  ffa9007f-02fe-44e3-ac93-c0543e0c8882  0
 912284fd-a0b6-42b7-8854-17b131ec8a06  2024-05-22T14:39:19Z  20GiB        0 B             9.2GiB                2676ce46-fa1e-4b40-ae62-164e11a5e3b1  0
 9c93df8b-22e9-4570-8d7c-7ba98812c2d2  2024-05-22T14:39:13Z  20GiB        9.2GiB          9.2GiB                2676ce46-fa1e-4b40-ae62-164e11a5e3b1  0
 a1596bc5-8610-42b3-9cab-9dfdcfd34c04  2024-05-22T14:39:12Z  20GiB        9.6GiB          9.6GiB                6898e456-087c-481a-9b47-f4424dba7499  0
 cb713c51-288a-44b7-9cbf-b283f466d2d3  2024-05-22T14:39:20Z  20GiB        812MiB          812MiB                a73c02e7-38dd-43fe-b7ee-37c908063175  0
 cc3cf207-984f-46f6-b320-7cec720b937a  2024-05-22T14:39:13Z  20GiB        2.1GiB          2.1GiB                831a75e4-f8c7-4285-a24a-34db1472eaa2  0
 f54cab20-e3f8-4950-87a1-f5a7ecc1ce38  2024-05-22T14:39:18Z  20GiB        824MiB          824MiB                c234c489-d441-4c93-abca-a58ff0beb232  0
 f7cac4d2-c66d-4c1e-aa03-3d000c9f4ec1  2024-05-22T14:39:20Z  8GiB         412MiB          412MiB                c36f7566-cb46-4da8-af65-9909ad254f0a  0
```

If I patch finalizer to null and delete them, will they be deleted from storage backend?

Also I do not have a snapshot controller, openebs install via helm.
according to this it should be installed https://blog.mayadata.io/openebs/openebs-snapshots-using-kubectl 
```
kubetcl get po -n openebs
NAME                                                                      
openebs-agent-core-9d5d8f769-kj4vm             
openebs-agent-ha-node-86cl6                    
openebs-agent-ha-node-8nkx4                    
openebs-agent-ha-node-bb6fb                    
openebs-agent-ha-node-f95ng                    
openebs-agent-ha-node-fqh7j                    
openebs-agent-ha-node-lqr7k                    
openebs-agent-ha-node-xgpdl                    
openebs-api-rest-65cbb47675-jpbf6              
openebs-csi-controller-556645d9d5-24566        
openebs-csi-node-6wx7x                         
openebs-csi-node-78zfg                         
openebs-csi-node-gt8sv                         
openebs-csi-node-lzwlb                         
openebs-csi-node-ncflc                         
openebs-csi-node-qnvhp                         
openebs-csi-node-skmgj                         
openebs-etcd-0                                 
openebs-io-engine-22x7w                        
openebs-io-engine-4w858                        
openebs-io-engine-drbll                        
openebs-io-engine-xkmr4                        
openebs-localpv-provisioner-6ddf7c7978-cc9dk   
openebs-loki-0                                 
openebs-nats-0                                 
openebs-nats-1                                 
openebs-nats-2                                 
openebs-nfs-provisioner-648d6d874f-jjzh4       
openebs-operator-diskpool-755dcfb96d-s9qnn     
openebs-promtail-56667                         
openebs-promtail-bnfgj                         
openebs-promtail-c27jx                         
openebs-promtail-gjf4t                         
openebs-promtail-jbdgz                         
openebs-promtail-lc2lb                         
openebs-promtail-xz92n 
```

**Comment by tiagolobocastro** [comment]
Hey @todeb
So let's see if I'm getting this right.
You have 0 volumesnapshots, 2 volumesnapshotcontent and 18 mayastor snapshots?
Something seems to have wrong here.

Would be able to take a dump? Example: `kubectl mayastor dump system -n $namspace`

**Comment by todeb** [comment]
Yes, I have 0 volumesnpashots. The deletion policy of volumesnapshotcontents was "Retain".
So volumesnapshots were deleted but volumesnapshotcontents not. I had patched volumesnapshotscontents policy to delete.
And Im trying to delete them, but just can't.

I have 18 volumesnapshotcontents and 18 mayastor snapshots. I just share not all of them in get snapshot command.

```
kubectl get volumesnapshotcontents | grep snap | wc -l
18
```
[mayastor-2024-06-05--11-26-04-UTC.tar.gz](https://github.com/user-attachments/files/15586194/mayastor-2024-06-05--11-26-04-UTC.tar.gz)

**Comment by tiagolobocastro** [comment]
Ah I see... 
Maybe changing the policy afterwards doesn't work?
I see this finalizer which is probably what's blocking its deletion:
`snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection`

@Abhinandan-Purkait any thoughts here?

**Comment by todeb** [comment]
is it possible at least to check if those snapshots exists on storage backend ?
If they are not exists then I can probably just force delete them from k8s and mayastor etcd.

But if they existing I need a bit help as well to delete them.

**Comment by tiagolobocastro** [comment]
Yes we can do that, delete from k8s and then delete from mayastor using curl.
Maybe @dsharma-dc or @abhilashshetty04 can help here. Otherwise I can come up with an example at EOW.

**Comment by tiagolobocastro** [comment]
Alright, first step would be to remove the finaliser and delete the desired snapshot CR's.
Then you can port-forward the rest, example:
> kubectl -n openebs port-forward svc/mayastor-api-rest 8081:8081

Then let's check one of the snapshots, example:
> curl -X GET http://localhost:8081/v0/volumes/snapshots/xxxxxxxxx | jq

If you're absolutely sure this is the right one to delete, then
> curl -X DELETE http://localhost:8081/v0/volumes/snapshots/xxxx

If you re-run the GET it should now yield not found.
And as you know, you can also check using: `kubectl-mayastor -n openebs get volume-snapshots`

Hope this helps

**Comment by todeb** [comment]
works, thank you.

**Comment by mc2285** [comment]
I kindly request to reopen, this very same problem happened to me on `openebs` `v4.2.0` yesterday also with `velero` for some reason. Could and option to manually delete a snapshot be added to `kubectl-openebs`? We have this option for volumes now so it would only be a logical consequence

**Comment by tiagolobocastro** [comment]
@mc2285 do you mean in your use case there's also no corresponding volumesnapshot/content CustomResource, but the volume snapshot still exists in the mayastor control-plane? ie you can list it via the plugin

**Comment by mc2285** [comment]
Yes, indeed. I've recently run into a situation where I had no `VolumeSnapshot`, a `VolumeSnapshotContent` that would not delete properly (had to remove `finalizers`, it was stuck deleting for ~5min) and I could list the snapshot itself via the plugin. I think it would make sense to implement snapshot delete in the plugin especially that snapshots can be destroyed via the grpc client but performing this action will lead to a dangling snapshot reference that has to be manually removed from etcd which I would rather not be doing every time I have to clean up a dangling snapshot. Maybe I should open a separate issue for that unexpected/messy behavior or is it by design and I am not supposed to be destroying snapshots via grpc client? I guess there is a REST API endpoint for that as with volume but I have failed to find relevant docs...

**Comment by tiagolobocastro** [comment]
If for some reason you can't delete the snapshot via CR deletion, then I'm not sure the CLI delete would be able to. Sounds like something is going awry there that needs to be sorted.

That being said, yes we still should have the CLI subcommand in case someone does force delete the CRs, so we should raise a ticket for that. Would mind raising a ticket for that?

I would kindly request you to also raise a ticket if you can't delete the snapshots gracefully via CR, with a support dump and we can take a look.

Yes deleting resources directly to io-engine and bypassing the control-plane can lead to some confusing state with stale etcd entries.
There's an api endpoint for deleting the snapshot, but I'd rather you use the plugin, which a few extra checks there, ex: is the corresponding CR really deleted
