### ISSUE TITLE
race condition of connect and disconnect in controller

### ISSUE THREAD

**Issue by MengjinWu** [openebs/mayastor#1682]
Hi, I am using Mayastor 23.01 version.

During the running of the preservation/reservation tests, there are some failures that occur, and the occurrence frequency of these failures is not high.

From the log of an io-engine, it shows the error in ctrl.c in spdk:
```
	if (admin_qpair->state != SPDK_NVMF_QPAIR_ACTIVE || admin_qpair->group == NULL) {
		/* There is a chance that admin qpair is being destroyed at this moment due to e.g.
		 * expired keep alive timer. Part of the qpair destruction process is change of qpair's
		 * state to DEACTIVATING and removing it from poll group */
		SPDK_ERRLOG("Inactive admin qpair (state %d, group %p)\n", admin_qpair->state, admin_qpair->group);
		SPDK_NVMF_INVALID_CONNECT_CMD(rsp, qid);
		spdk_nvmf_request_complete(req);
		return;
	}
```
The error shows:
`Inactive admin qpair (state 3, group (nil))`

the status 3(SPDK_NVMF_QPAIR_ERROR) means that the qpair is at disconnecting process.

However, the error log shows that some one is trying to connect to the qpair.

**Comment by tiagolobocastro** [comment]
Hi, which branch is this happening on?

**Comment by MengjinWu** [comment]
> Hi, which branch is this happening on?

I am on v23.01.

**Comment by tiagolobocastro** [comment]
I meant develop, release/xxxx ?

**Comment by MengjinWu** [comment]
release/2.4

**Comment by tiagolobocastro** [comment]
I would suggest using a more recent version, example release/2.6 or release/2.7

**Comment by tiagolobocastro** [comment]
Did you try the more recent version @MengjinWu ?
