### ISSUE TITLE
bitnami/bitnami-shell deprecated will be removed July 2024

### ISSUE THREAD

**Issue by ThorbenJ** [openebs/mayastor#1689]
**Describe the bug**
While trying to debug why ectd won't start on arm64, I found the initcontain is using an old image version: bitnami/bitnami-shell:11-debian-11-r63
This version lacks arm64, the latest version 11-debian-11-r99 has both arm64 and amd64.
However the bigger issue maybe: 

> 🛑 Deprecation Notice
>
>The Bitnami Shell container is no longer maintained and is now deprecated in favor of [OS Shell](https://hub.docker.com/r/bitnami/os-shell). This image will no longer be released in our catalog, but already released container images will persist in the registries until July 2024.
>
>After that time, this repository will be fully removed in favor of [bitnami/bitnami-shell-archived](https://hub.docker.com/r/bitnami/bitnami-shell-archived) where all existing images can be found.

I note the latest os-shell supports both amd64 and arm64 too. 

Read https://hub.docker.com/r/bitnami/bitnami-shell

** OS info (please complete the following information):**
 - Distro: Debian/Armbian stable
 - Kernel version: 6.8
 - MayaStor revision v2.7.0

**Additional context**
I imagine amd64 deployments will start breaking when they pull the images from the registry.
Silver linning for me, upgrading to a newer image (os-shell for example) would win my arm64 support =)

**Comment by ThorbenJ** [comment]
I updated the etcd statefulset to use:
os-shell:12-debian-12-r25
etcd:3.5.14-debian-12-r4

**Comment by tiagolobocastro** [comment]
Hey @ThorbenJ, coincidentally the next releases should hopefully not be using those (https://github.com/openebs/mayastor-extensions/commit/cbc271819a44a258762ece42b0c899c3542f9eb4)
Though I think we'll have to check, there may be something else using them.

We also had a request to explicitly list which images we require (for air-gapped) and I've been thinking about adding this list plus a test to ensure the list remains correct, maybe we can then check if there's any other use of bitnami-shell.

**Comment by avishnu** [comment]
The fix is available in the develop charts and will be part of the v4.2 release.

**Comment by tiagolobocastro** [comment]
Fixed on v2.7.2
