### ISSUE TITLE
CSI failed to attach volume

### ISSUE THREAD

**Issue by veenadong** [openebs/mayastor#1712]
Mayastor 2.5.1 on 3 nodes.
Creating a PVC is successful, but pods are not running due to:

```
Events:
  Type     Reason              Age                 From                     Message
  ----     ------              ----                ----                     -------
  Warning  FailedAttachVolume  23s (x45 over 76m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-8609b23a-8228-43c9-9056-60f234be21f5" : CSINode gl-dpce-r0-host-onprem3.dpce-sc.private does not contain driver io.openebs.csi-mayastor
```

CSI controller is logging:

`I0805 19:05:07.361280       1 csi_handler.go:251] Attaching "csi-6f33930df7fdef795d0440162ee726ea5919fb36a38104c65d36f86df29b17b3"
I0805 19:05:07.377038       1 csi_handler.go:234] Error processing "csi-6f33930df7fdef795d0440162ee726ea5919fb36a38104c65d36f86df29b17b3": failed to attach: CSINode gl-dpce-r0-host-onprem3.dpce-sc.private does not contain driver io.openebs.csi-mayastor`

Attached is the CSI controller log
[csi.log](https://github.com/user-attachments/files/16513999/csi.log)

**Comment by Abhinandan-Purkait** [comment]
@veenadong Is the csi-node pod running on the node where the application is scheduled?

**Comment by Abhinandan-Purkait** [comment]
`gl-dpce-r0-host-onprem3.dpce-sc.private` Can you share the pods on this node in the `<mayastor namespace>`?

**Comment by veenadong** [comment]
> @veenadong Is the csi-node pod running on the node where the application is scheduled?

Yes, the pod is running on this node.  I checked all the pods in the mayastor namespace, all pods (io-engine, etc) are all running.

Restarting the csi-node pod on "gl-dpce-r0-host-onprem3.dpce-sc.private" recovered the cluster.

**Comment by Abhinandan-Purkait** [comment]
@veenadong Is this resolved? I believe it could have been some issue with the prerequisites check that we have, but might have got fixed on the restart.

**Comment by tiagolobocastro** [comment]
> @veenadong Is this resolved? I believe it could have been some issue with the prerequisites check that we have, but might have got fixed on the restart.

Yes, csi-node needs to be running..

Please reopen if this pops up again, including logs from csi-node
