### ISSUE TITLE
Mayastor volume is corrupted after recovering from nodes down

### ISSUE THREAD

**Issue by veenadong** [openebs/mayastor#1713]
Mayastor 2.5.1:

We took two nodes down and the 3rd node was running for 6 hours.  The 2 nodes were brought up, all mayastor pods are running, however, the volume is corrupted.

Pod status:

`Warning  FailedMount  32s (x286 over 9h)  kubelet  MountVolume.SetUp failed for volume "pvc-5b25da79-84d3-4f41-8718-5f4c8028d9c0" : applyFSGroup failed for vol 5b25da79-84d3-4f41-8718-5f4c8028d9c0: lstat /var/snap/microk8s/common/var/lib/kubelet/pods/0ae8db7a-d1e4-4288-b4a2-25f33ea81573/volumes/kubernetes.io~csi/pvc-5b25da79-84d3-4f41-8718-5f4c8028d9c0/mount/checks/872aa64ed9513ccdd42b81106223c5bff7efb2b49e05b426ac5bdea1c91a63d2: structure needs cleaning`

ls on the directory:

```
core@sc-os-72-node3:~$ sudo ls -alR /var/snap/microk8s/common/var/lib/kubelet/pods/0ae8db7a-d1e4-4288-b4a2-25f33ea81573/volumes/kubernetes.io~csi/pvc-5b25da79-84d3-4f41-8718-5f4c8028d9c0/mount/checks/
/var/snap/microk8s/common/var/lib/kubelet/pods/0ae8db7a-d1e4-4288-b4a2-25f33ea81573/volumes/kubernetes.io~csi/pvc-5b25da79-84d3-4f41-8718-5f4c8028d9c0/mount/checks/:
ls: cannot access '/var/snap/microk8s/common/var/lib/kubelet/pods/0ae8db7a-d1e4-4288-b4a2-25f33ea81573/volumes/kubernetes.io~csi/pvc-5b25da79-84d3-4f41-8718-5f4c8028d9c0/mount/checks/872aa64ed9513ccdd42b81106223c5bff7efb2b49e05b426ac5bdea1c91a63d2': Structure needs cleaning
ls: cannot access '/var/snap/microk8s/common/var/lib/kubelet/pods/0ae8db7a-d1e4-4288-b4a2-25f33ea81573/volumes/kubernetes.io~csi/pvc-5b25da79-84d3-4f41-8718-5f4c8028d9c0/mount/checks/4679c07e42c366f79eec31d486f03f25ca6a4218dc872f6f13193da69cea54c9': Bad message
total 16
drwxrws--- 3 _apt core 4096 Aug  6 22:23 .
drwxrwsr-x 7 root core 4096 Aug  6 19:29 ..
-????????? ? ?    ?       ?            ? 4679c07e42c366f79eec31d486f03f25ca6a4218dc872f6f13193da69cea54c9
-????????? ? ?    ?       ?            ? 872aa64ed9513ccdd42b81106223c5bff7efb2b49e05b426ac5bdea1c91a63d2
-rw------- 1 _apt core 1240 Aug  6 22:23 9b4b05d5573af275c60f4882b64370408b21c4648bb754c6d3dde96f51b233d3
drwxrws--- 2 _apt core 4096 Aug  6 22:44 state

/var/snap/microk8s/common/var/lib/kubelet/pods/0ae8db7a-d1e4-4288-b4a2-25f33ea81573/volumes/kubernetes.io~csi/pvc-5b25da79-84d3-4f41-8718-5f4c8028d9c0/mount/checks/state:
total 12
drwxrws--- 2 _apt core 4096 Aug  6 22:44 .
drwxrws--- 3 _apt core 4096 Aug  6 22:23 ..
-rw------- 1 _apt core  123 Aug  6 22:44 9b4b05d5573af275c60f4882b64370408b21c4648bb754c6d3dde96f51b233d3
```

Attaching is the system dump from all 3 nodes:
[sc-os-72-node1-mayastor-dump.tar.gz](https://github.com/user-attachments/files/16532588/sc-os-72-node1-mayastor-dump.tar.gz)
[sc-os-72-node2-mayastor-dump.tar.gz](https://github.com/user-attachments/files/16532589/sc-os-72-node2-mayastor-dump.tar.gz)
[sc-os-72-node3-mayastor-dump.tar.gz](https://github.com/user-attachments/files/16532590/sc-os-72-node3-mayastor-dump.tar.gz)

**Comment by veenadong** [comment]
Could someone tell me how to recover the volume?  The cluster is down due to file corruption

**Comment by tiagolobocastro** [comment]
I would recommend you switch to v2.7.0 as 2.5.1 had a few bugs which were seen to cause some of the errors I see on your logs.
As for the volume not mounting, we never seen that, was the node where the volume was mounted force shutdown or something?

Anyhow I recommend you delete the application using the volume and then:

1. Port forward rest: `kubectl -n mayastor port-forward svc/mayastor-api-rest 8081:8081`
2. Manually publish the volume into one of your nodes, and get device uri:
```
curl -X PUT 'http://localhost:8081/v0/volumes/ec4e66fd-3b33-4439-b504-d49aba53da26/target' -H 'Content-Type: application/json' -d '{"node": "io-engine-1", "protocol": "nvmf", "republish": false, "reuse_existing": false}' | jq '.state.target.deviceUri'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1246  100  1158  100    88  82602   6277 --:--:-- --:--:-- --:--:-- 95846
"nvmf://10.1.0.5:8420/nqn.2019-05.io.openebs:ec4e66fd-3b33-4439-b504-d49aba53da26"
```
3. ssh into the node, and connect via nvme cli: 
```
sudo nvme connect -t tcp -s 8420 -a 10.1.0.5 -n nqn.2019-05.io.openebs:ec4e66fd-3b33-4439-b504-d49aba53da26
connecting to device: nvme3
ls /dev/disk/by-id/nvme-uuid.ec4e66fd-3b33-4439-b504-d49aba53da26
/dev/disk/by-id/nvme-uuid.ec4e66fd-3b33-4439-b504-d49aba53da26
```
4. You can now run your filesystem recovery tools,
5. Disconnect: `sudo nvme disconnect -n nqn.2019-05.io.openebs:ec4e66fd-3b33-4439-b504-d49aba53da26`
6. Unpublish: `curl -X DELETE 'http://localhost:8081/v0/volumes/ec4e66fd-3b33-4439-b504-d49aba53da26/target'`

Hope this helps

**Comment by tiagolobocastro** [comment]
Please reopen if more info is needed

**Comment by todeb** [comment]
@tiagolobocastro just had the similar error msg on 2.7.3
kubelet            MountVolume.SetUp failed for volume "pvc-264f6369-c8ac-4576-9220-fd5438335475" : applyFSGroup failed for vol 264f6369-c8ac-4576-9220-fd5438335475: lstat /var/lib/kubelet/pods/5a4bee50-6332-4e85-9b78-8551c0ff2d7e/volumes/kubernetes.io~csi/pvc-264f6369-c8ac-4576-9220-fd5438335475/mount: input/output error

after node was rebooted.

**Comment by todeb** [comment]
after deleted the volumeattachment and force deleted pod:

```MountVolume.SetUp failed for volume "pvc-264f6369-c8ac-4576-9220-fd5438335475" : rpc error: code = InvalidArgument desc = Failed to publish volume 264f6369-c8ac-4576-9220-fd5438335475: no mount for staging path /var/lib/kubelet/plugins/kubernetes.io/csi/io.openebs.csi-mayastor/419f9ab7acc62440f46f83717cac7198b4f7a5bb42fff4484bafb2bf892c4fbb/globalmount```

**Comment by todeb** [comment]
scaling sts down and up seems to fix that issue.

**Comment by tiagolobocastro** [comment]
Can you consistently reproduce this @todeb?
If you, could you try restarting the kubelet as an alternative and see if that helps?

**Comment by todeb** [comment]
will try, in my case nothing was corrupted at least.
Im using already rke1 cluster which has kubelet running as docker container, so I suspect that might also cause some undetermined issues.

**Comment by todeb** [comment]
@tiagolobocastro issue occurred again, kubelet restart is not solving issue, node reboot neither.
I rather do not want to scale sts.
Is there any other option that can help?

**Comment by tiagolobocastro** [comment]
Could you attach a support dump here?

**Comment by todeb** [comment]
After node restarts I think most logs are gone. But still there are some issues, 2 volumes are degraded, with out of space mark, but they are not out of space.

```
 a2ff6f53-b6e3-43b7-9c30-9ff29af0de1d  d077b18d-8ec4-4a88-8180-f9b309d3efaa  rke-prod-215-bm  pool-on-prod-215-bm  Online  <none>     190 GiB   158.2 GiB  0 B        Degraded      OutOfSpace  <none>   <none>
 ae8054bb-29b5-4696-b0d5-c6713f9547c4  a56db237-d6dc-4f30-9cbc-2aeda7e07255  rke-prod-215-bm  pool-on-prod-215-bm  Online  <none>     500 GiB   374.6 GiB  0 B        Degraded      OutOfSpace  <none>   <none>
```

[mayastor-2026-01-13--15-54-53-UTC.tar.gz](https://github.com/user-attachments/files/24594647/mayastor-2026-01-13--15-54-53-UTC.tar.gz)

**Comment by tiagolobocastro** [comment]
How odd, volume topology was not collected it seems... perhaps a bug from the support bundle ?
But it does seem does pools are fully used?
```
"state": {
      "capacity": 1098433691648,
      "disks": [
        "uring:///dev/ubuntu-vg/mayastor?uuid=22e708e0-9780-4f96-b8d2-1c960cdd2ef4"
      ],
      "id": "pool-on-prod-215-bm",
      "node": "rke-prod-215-bm",
      "status": "Online",
      "used": 1098433691648,
      "committed": 1472100040704,
      "encrypted": false
    }
```
capacity == used

**Comment by todeb** [comment]
yes, I found out this as well yesterday.
I used:
```
kubectl get diskpool -n openebs
```
which is giving totally wrong numbers on openebs-4.1.3
but 
```
kubectl mayastor get pools -n openebs
```
and openebs metrics are correct.
On other clusters with newer mayastor not seeing such issue.
And the problem above you right is full pool. Resolved now.
