### ISSUE TITLE
I/O type 'Flush' not supported by at least one of child devices

### ISSUE THREAD

**Issue by mrvnklm** [openebs/mayastor#1750]
**Describe the bug**
getting the following error in io-engine pod with high cpu usage
```
[2024-10-07T17:44:14.832745163+00:00  INFO io_engine::bdev::nexus::nexus_bdev:nexus_bdev.rs:1170] Nexus 'ba068991-3046-4a34-83bc-1c98ba3625da' [open]: I/O type 'Flush' not supported by at least one of child devices
```

**OS info:**
 - Distro: `Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-45-generic x86_64) with MicroK8s v1.30.5 revision 7232`
 - Kernel: `Linux n1 6.8.0-45-generic 45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
 - MayaStor: `2.0.0-microk8s-1b`

**Additional context**
I have only one instance of mariadb-galera with 3 replicas running. The disk I am using is a virtual disk which the hoster calls local block storage

edit:
`microk8s mayastor-pools add --node uk8s-1 --size 20GB` on my root disk causes the same issue

**Comment by tiagolobocastro** [comment]
Unfortunately today, high cpu usage is expected, see https://github.com/openebs/mayastor/issues/1745 for tracking interrupt mode enhancement request.

**Comment by tiagolobocastro** [comment]
Please follow the other ticket for updates on interrupt mode enhancement.
