### ISSUE TITLE
OpenEBS on OpenShift - etcd doesn't start up with "Headless service domain does not have an IP per initial member in the cluster"

### ISSUE THREAD

**Issue by FamilieRo** [openebs/mayastor#1778]
Hi!

My issue seems to be a little like issue #1421 

We are using an OpenShift cluster with 3 master and 2 worker nodes. 
I installed OpenEbs via helm chart like described here:
[https://openebs.io/docs/quickstart-guide/installation#installation-via-helm](url)

Before installing OpenEBS I checked the prerequisites and labeled my worker nodes as described in the documentation. I also created the namespace before and set the permissions. 

After that I ran this command:
helm install openebs --namespace openebs openebs/openebs --set openebs-crds.csi.volumeSnapshots.enabled=false --set lvm-localpv.crds.lvmLocalPv.enabled=false --set zfs-localpv.crds.zfsLocalPv.enabled=false --set mayastor.etcd.clusterDomain="FQDN of my cluster"

The command succesfully finished but the 3 etcd pods does not come up. I only get the error message:
etcd Timestamp ERROR ==> Headless service domain does not have an IP per initial member in the cluster

I tried to uninstall and install the chart again. 
I also tried to decrease the replicas and I also tried to set the parameter etcd.initialClusterState to "existing" with no luck. 

What can I do to get the etcd pods up and running?

**Comment by tiagolobocastro** [comment]
Hi @FamilieRo,

Would you be able to take a support bundle?
https://openebs.io/docs/user-guides/replicated-storage-user-guide/replicated-pv-mayastor/advanced-operations/supportability

There's a bug on the kubectl-plugin when collecting logs. To get around this you can use the plugin binary from the RC version:
https://github.com/openebs/mayastor/releases/tag/v2.7.2-rc.1

Also btw, did you follow the guide from the docs? https://openebs.io/docs/Solutioning/openebs-on-kubernetes-platforms/openshift

**Comment by FamilieRo** [comment]
Hi @tiagolobocastro ,

yes, I followed the documentation you mentioned, checked the requirements and set the needed permissions. 

I am able to get a support bundle with the rc-plugin. But the tool cannot collect anything for the etcd-pods because they do not come up. All I get is this:

> .[38;5;6metcd .[38;5;5m11:19:11.98 .[0m
> .[38;5;6metcd .[38;5;5m11:19:11.98 .[0m.[1mWelcome to the Bitnami etcd container.[0m
> .[38;5;6metcd .[38;5;5m11:19:11.98 .[0mSubscribe to project updates by watching .[1mhttps://github.com/bitnami/containers.[0m
> .[38;5;6metcd .[38;5;5m11:19:11.98 .[0mSubmit issues and feature requests at .[1mhttps://github.com/bitnami/containers/issues.[0m
> .[38;5;6metcd .[38;5;5m11:19:11.98 .[0m
> .[38;5;6metcd .[38;5;5m11:19:11.99 .[0m.[38;5;2mINFO .[0m ==> ** Starting etcd setup **
> .[38;5;6metcd .[38;5;5m11:19:12.00 .[0m.[38;5;2mINFO .[0m ==> Validating settings in ETCD_* env vars..
> .[38;5;6metcd .[38;5;5m11:19:12.00 .[0m.[38;5;3mWARN .[0m ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
> .[38;5;6metcd .[38;5;5m11:19:12.00 .[0m.[38;5;2mINFO .[0m ==> Initializing etcd
> .[38;5;6metcd .[38;5;5m11:19:12.00 .[0m.[38;5;2mINFO .[0m ==> Generating etcd config file using env variables
> .[38;5;6metcd .[38;5;5m11:19:12.01 .[0m.[38;5;2mINFO .[0m ==> There is no data from previous deployments
> .[38;5;6metcd .[38;5;5m11:19:12.01 .[0m.[38;5;2mINFO .[0m ==> Bootstrapping a new cluster
> .[38;5;6metcd .[38;5;5m11:20:12.07 .[0m.[38;5;1mERROR.[0m ==> Headless service domain does not have an IP per initial member in the cluster


Do you need more infos? I do not want to upload the entire dump because there are a lot of cluster informations that I do not want to share if not needed.

**Comment by tiagolobocastro** [comment]
Is your networking working well in general? Can you deploy other solutions which make use of headless services?

Would this be of relevance: https://github.com/openebs/mayastor/issues/1421#issuecomment-1763358876 ?

You you be able to run:
> kubectl -n openebs get ep openebs-etcd-headless
> kubectl -n openebs get ep openebs-etcd-headless -o yaml

Also, maybe something like:
```
kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
# wait till ready
kubectl exec -i -t dnsutils -- nslookup kubernetes.default
kubectl exec -ti dnsutils -- cat /etc/resolv.conf
kubectl exec -ti dnsutils -- nslookup openebs-etcd-headless.openebs.svc.cluster.local
kubectl exec -ti dnsutils -- nslookup openebs-etcd-headless.openebs.svc.$YOUR-DOMAIN
```
More info on: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by FamilieRo** [comment]
Hi,

DNS seems to work like expected:

> kubectl exec -i -t dnsutils -- nslookup kubernetes.default
> kubectl exec -ti dnsutils -- cat /etc/resolv.conf
> kubectl exec -ti dnsutils -- nslookup openebs-etcd-headless.openebs.svc.cluster.local
> kubectl exec -ti dnsutils -- nslookup openebs-etcd-headless.openebs.svc.CLUSTER.FQDN
> Server:         172.30.0.10
> Address:        172.30.0.10#53
> 
> Name:   kubernetes.default.svc.cluster.local
> Address: 172.30.0.1
> 
> search default.svc.cluster.local svc.cluster.local cluster.local FQDN DOMAIN
> nameserver 172.30.0.10
> options ndots:5
> Server:         172.30.0.10
> Address:        172.30.0.10#53
> 
> Name:   openebs-etcd-headless.openebs.svc.cluster.local
> Address: 10.128.3.23
> Name:   openebs-etcd-headless.openebs.svc.cluster.local
> Address: 10.129.2.217
> 
> Server:         172.30.0.10
> Address:        172.30.0.10#53
> 
> Name:   openebs-etcd-headless.openebs.svc.CLUSTER.FQDN
> Address: 10.82.28.10

> kubectl -n openebs get ep openebs-etcd-headless -o yaml
> apiVersion: v1
> kind: Endpoints
> metadata:
>   creationTimestamp: "2024-12-08T09:09:49Z"
>   labels:
>     app.kubernetes.io/instance: openebs
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/name: etcd
>     helm.sh/chart: etcd-8.6.0
>     service.kubernetes.io/headless: ""
>   name: openebs-etcd-headless
>   namespace: openebs
>   resourceVersion: "42059773"
>   uid: 63b46ee5-aaa9-4f69-a2b3-2ca485c6a240
> subsets:
> - addresses:
>   - hostname: openebs-etcd-1
>     ip: 10.128.3.27
>     nodeName: Node1
>     targetRef:
>       kind: Pod
>       name: openebs-etcd-1
>       namespace: openebs
>       uid: a2f28099-cbfd-4444-9e95-15f7bb2fcc7a
>   - hostname: openebs-etcd-0
>     ip: 10.129.2.221
>     nodeName: Node2
>     targetRef:
>       kind: Pod
>       name: openebs-etcd-0
>       namespace: openebs
>       uid: 2d69a4c2-9c2d-4ea7-a867-8199dc9d8b19
>   ports:
>   - name: peer
>     port: 2380
>     protocol: TCP
>   - name: client
>     port: 2379
>     protocol: TCP


I also checked the issue you mentioned. Setting the cluster state to "existing" only result in this log entries:

> .[38;5;6metcd .[38;5;5m09:38:01.66 .[0m
> .[38;5;6metcd .[38;5;5m09:38:01.66 .[0m.[1mWelcome to the Bitnami etcd container.[0m
> .[38;5;6metcd .[38;5;5m09:38:01.66 .[0mSubscribe to project updates by watching .[1mhttps://github.com/bitnami/containers.[0m
> .[38;5;6metcd .[38;5;5m09:38:01.66 .[0mSubmit issues and feature requests at .[1mhttps://github.com/bitnami/containers/issues.[0m
> .[38;5;6metcd .[38;5;5m09:38:01.66 .[0m
> .[38;5;6metcd .[38;5;5m09:38:01.66 .[0m.[38;5;2mINFO .[0m ==> ** Starting etcd setup **
> .[38;5;6metcd .[38;5;5m09:38:01.67 .[0m.[38;5;2mINFO .[0m ==> Validating settings in ETCD_* env vars..
> .[38;5;6metcd .[38;5;5m09:38:01.67 .[0m.[38;5;3mWARN .[0m ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
> .[38;5;6metcd .[38;5;5m09:38:01.68 .[0m.[38;5;2mINFO .[0m ==> Initializing etcd
> .[38;5;6metcd .[38;5;5m09:38:01.68 .[0m.[38;5;2mINFO .[0m ==> Generating etcd config file using env variables
> .[38;5;6metcd .[38;5;5m09:38:01.68 .[0m.[38;5;2mINFO .[0m ==> There is no data from previous deployments
> .[38;5;6metcd .[38;5;5m09:38:01.68 .[0m.[38;5;2mINFO .[0m ==> Adding new member to existing cluster
> .[38;5;6metcd .[38;5;5m09:38:01.71 .[0m.[38;5;3mWARN .[0m ==> Cluster not healthy, not adding self to cluster for now, keeping trying...
> .[38;5;6metcd .[38;5;5m09:38:11.72 .[0m.[38;5;3mWARN .[0m ==> Cluster not healthy, not adding self to cluster for now, keeping trying...
> .[38;5;6metcd .[38;5;5m09:38:21.74 .[0m.[38;5;3mWARN .[0m ==> Cluster not healthy, not adding self to cluster for now, keeping trying...
> .[38;5;6metcd .[38;5;5m09:38:31.76 .[0m.[38;5;3mWARN .[0m ==> Cluster not healthy, not adding self to cluster for now, keeping trying...
> 

Changing the replica count does also not work. 

I also checked the host file system and the etcd has a data folder with appropiate permissions set.

**Comment by tiagolobocastro** [comment]
Hmm seems your headless service only has 2 IPs? Thus explaining the problem?

**Comment by tiagolobocastro** [comment]
Is your pod `openebs-etcd-2` in running state?

**Comment by FamilieRo** [comment]
No, it is in init and does nothing. Only openebs-etcd-0 and openebs-etcd-1 are running but both report the same error.

**Comment by tiagolobocastro** [comment]
Could you please share `kubectl -n openebs get pod openebs-etcd-2 -o yaml` ?

**Comment by FamilieRo** [comment]
I uninstalled and installed the helm chart and fpr now the etcd1 is only in init mode. Here is the output:

> kubectl -n openebs get pod openebs-etcd-1 -o yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   annotations:
>     checksum/token-secret: 017f8f0fdaca690cfd382bd83c3f4365971180f175084dabddf9f23e2b420640
>     openshift.io/scc: privileged
>   creationTimestamp: "2024-12-08T10:49:39Z"
>   generateName: openebs-etcd-
>   labels:
>     app: etcd
>     app.kubernetes.io/instance: openebs
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/name: etcd
>     apps.kubernetes.io/pod-index: "1"
>     controller-revision-hash: openebs-etcd-7ffc675d47
>     helm.sh/chart: etcd-8.6.0
>     openebs.io/logging: "true"
>     statefulset.kubernetes.io/pod-name: openebs-etcd-1
>   name: openebs-etcd-1
>   namespace: openebs
>   ownerReferences:
>   - apiVersion: apps/v1
>     blockOwnerDeletion: true
>     controller: true
>     kind: StatefulSet
>     name: openebs-etcd
>     uid: 6ddeda37-ab95-4069-a9e0-47c95ea4a142
>   resourceVersion: "42096703"
>   uid: 37a31bbe-4c22-471d-954e-cff447ab1ce2
> spec:
>   affinity:
>     podAntiAffinity:
>       requiredDuringSchedulingIgnoredDuringExecution:
>       - labelSelector:
>           matchLabels:
>             app.kubernetes.io/instance: openebs
>             app.kubernetes.io/name: etcd
>         topologyKey: kubernetes.io/hostname
>   containers:
>   - env:
>     - name: BITNAMI_DEBUG
>       value: "false"
>     - name: MY_POD_IP
>       valueFrom:
>         fieldRef:
>           apiVersion: v1
>           fieldPath: status.podIP
>     - name: MY_POD_NAME
>       valueFrom:
>         fieldRef:
>           apiVersion: v1
>           fieldPath: metadata.name
>     - name: MY_STS_NAME
>       value: openebs-etcd
>     - name: ETCDCTL_API
>       value: "3"
>     - name: ETCD_ON_K8S
>       value: "yes"
>     - name: ETCD_START_FROM_SNAPSHOT
>       value: "no"
>     - name: ETCD_DISASTER_RECOVERY
>       value: "no"
>     - name: ETCD_NAME
>       value: $(MY_POD_NAME)
>     - name: ETCD_DATA_DIR
>       value: /bitnami/etcd/data
>     - name: ETCD_LOG_LEVEL
>       value: info
>     - name: ALLOW_NONE_AUTHENTICATION
>       value: "yes"
>     - name: ETCD_AUTH_TOKEN
>       value: jwt,priv-key=/opt/bitnami/etcd/certs/token/jwt-token.pem,sign-method=RS256,ttl=10m
>     - name: ETCD_ADVERTISE_CLIENT_URLS
>       value: http://$(MY_POD_NAME).openebs-etcd-headless.openebs.svc.acme.inc:2379,http://openebs-etcd.openebs.svc.acme.inc:2379
>     - name: ETCD_LISTEN_CLIENT_URLS
>       value: http://0.0.0.0:2379
>     - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
>       value: http://$(MY_POD_NAME).openebs-etcd-headless.openebs.svc.acme.inc:2380
>     - name: ETCD_LISTEN_PEER_URLS
>       value: http://0.0.0.0:2380
>     - name: ETCD_AUTO_COMPACTION_MODE
>       value: revision
>     - name: ETCD_AUTO_COMPACTION_RETENTION
>       value: "100"
>     - name: ETCD_INITIAL_CLUSTER_TOKEN
>       value: etcd-cluster-k8s
>     - name: ETCD_INITIAL_CLUSTER_STATE
>       value: new
>     - name: ETCD_INITIAL_CLUSTER
>       value: openebs-etcd-0=http://openebs-etcd-0.openebs-etcd-headless.openebs.svc.acme.inc:2380,openebs-etcd-1=http://openebs-etcd-1.openebs-etcd-headless.openebs.svc.acme.inc:2380,openebs-etcd-2=http://openebs-etcd-2.openebs-etcd-headless.openebs.svc.acme.inc:2380
>     - name: ETCD_CLUSTER_DOMAIN
>       value: openebs-etcd-headless.openebs.svc.acme.inc
>     - name: ETCD_QUOTA_BACKEND_BYTES
>       value: "8589934592"
>     image: docker.io/bitnami/etcd:3.5.6-debian-11-r10
>     imagePullPolicy: IfNotPresent
>     livenessProbe:
>       exec:
>         command:
>         - /opt/bitnami/scripts/etcd/healthcheck.sh
>       failureThreshold: 5
>       initialDelaySeconds: 60
>       periodSeconds: 30
>       successThreshold: 1
>       timeoutSeconds: 5
>     name: etcd
>     ports:
>     - containerPort: 2379
>       name: client
>       protocol: TCP
>     - containerPort: 2380
>       name: peer
>       protocol: TCP
>     readinessProbe:
>       exec:
>         command:
>         - /opt/bitnami/scripts/etcd/healthcheck.sh
>       failureThreshold: 5
>       initialDelaySeconds: 60
>       periodSeconds: 10
>       successThreshold: 1
>       timeoutSeconds: 5
>     resources: {}
>     securityContext:
>       allowPrivilegeEscalation: false
>       runAsNonRoot: true
>       runAsUser: 1001
>     terminationMessagePath: /dev/termination-log
>     terminationMessagePolicy: File
>     volumeMounts:
>     - mountPath: /bitnami/etcd
>       name: data
>     - mountPath: /opt/bitnami/etcd/certs/token/
>       name: etcd-jwt-token
>       readOnly: true
>     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
>       name: kube-api-access-zdmwt
>       readOnly: true
>   dnsPolicy: ClusterFirst
>   enableServiceLinks: true
>   hostname: openebs-etcd-1
>   imagePullSecrets:
>   - name: default-dockercfg-x2brb
>   initContainers:
>   - command:
>     - /bin/bash
>     - -ec
>     - |
>       chown -R 1001:1001 /bitnami/etcd
>     image: docker.io/bitnami/bitnami-shell:11-debian-11-r63
>     imagePullPolicy: IfNotPresent
>     name: volume-permissions
>     resources: {}
>     securityContext:
>       runAsUser: 0
>     terminationMessagePath: /dev/termination-log
>     terminationMessagePolicy: File
>     volumeMounts:
>     - mountPath: /bitnami/etcd
>       name: data
>     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
>       name: kube-api-access-zdmwt
>       readOnly: true
>   preemptionPolicy: PreemptLowerPriority
>   priority: 0
>   restartPolicy: Always
>   schedulerName: default-scheduler
>   securityContext:
>     fsGroup: 1001
>   serviceAccount: default
>   serviceAccountName: default
>   subdomain: openebs-etcd-headless
>   terminationGracePeriodSeconds: 30
>   tolerations:
>   - effect: NoExecute
>     key: node.kubernetes.io/not-ready
>     operator: Exists
>     tolerationSeconds: 300
>   - effect: NoExecute
>     key: node.kubernetes.io/unreachable
>     operator: Exists
>     tolerationSeconds: 300
>   volumes:
>   - name: data
>     persistentVolumeClaim:
>       claimName: data-openebs-etcd-1
>   - name: etcd-jwt-token
>     secret:
>       defaultMode: 256
>       secretName: openebs-etcd-jwt-token
>   - name: kube-api-access-zdmwt
>     projected:
>       defaultMode: 420
>       sources:
>       - serviceAccountToken:
>           expirationSeconds: 3607
>           path: token
>       - configMap:
>           items:
>           - key: ca.crt
>             path: ca.crt
>           name: kube-root-ca.crt
>       - downwardAPI:
>           items:
>           - fieldRef:
>               apiVersion: v1
>               fieldPath: metadata.namespace
>             path: namespace
>       - configMap:
>           items:
>           - key: service-ca.crt
>             path: service-ca.crt
>           name: openshift-service-ca.crt
> status:
>   conditions:
>   - lastProbeTime: null
>     lastTransitionTime: "2024-12-08T10:49:39Z"
>     message: '0/5 nodes are available: 1 node(s) didn''t match pod anti-affinity rules,
>       1 node(s) had volume node affinity conflict, 3 node(s) had untolerated taint
>       {node-role.kubernetes.io/master: }. preemption: 0/5 nodes are available: 1 No
>       preemption victims found for incoming pod, 4 Preemption is not helpful for scheduling.'
>     reason: Unschedulable
>     status: "False"
>     type: PodScheduled
>   phase: Pending
>   qosClass: BestEffort

The error message is very interesting. We only have 2 worker nodes and as far as I understood the documentation I only have to label the worker nodes which will have the local storage attached with the label "openebs.io/engine=mayastor"
But then only 2 nodes are available and as far as I can see the etcd will have to run on 3 different nodes?
Can I label the master nodes to host the etcd pods only?
I found something about csi.node.topology.nodeSelector: true and csi.node.topology.segments but with no explanation...

**Comment by Abhinandan-Purkait** [comment]
Yeah, I think that's worth a try to use the master nodes to host the etcd pods, probably with tolerations and node selectors and get 3 instances of etcd pod running. You can set these values https://github.com/openebs/mayastor-extensions/blob/ece2e0b95294602252b95fb4771081a3283b243b/chart/values.yaml#L541 and https://github.com/openebs/mayastor-extensions/blob/ece2e0b95294602252b95fb4771081a3283b243b/chart/values.yaml#L558 on the helm chart for that.

For example like this, if you are using mayastor standalone chart.

```--set-json etcd={"replicaCount":"3","nodeSelector":{"key":"value"},"tolerations":[{"key":"node-role.kubernetes.io/control-plane"},{"key":"node-role.kubernetes.io/master"}]}```

**Comment by tiagolobocastro** [comment]
Just to clarify, on the nodeSelector, it could be a generic label shared by the nodes where you want to run etcd on (example: could be a label to allow them to run on the master nodes if you have 3 of those (not hostname though))

**Comment by FamilieRo** [comment]
Hi,
I labeled the master nodes with an extra label.
Then I created a custom values.yaml:

> openebs-crds:
>   csi:
>     volumeSnapshots:
>       enabled: false
>       keep: true
> 
> localpv-provisioner:
>   rbac:
>     create: true
> 
> zfs-localpv:
>   crds:
>     zfsLocalPv:
>       enabled: false
>     csi:
>       volumeSnapshots:
>         enabled: false
> 
> lvm-localpv:
>   crds:
>     lvmLocalPv:
>       enabled: false
>     csi:
>       volumeSnapshots:
>         enabled: false
> 
> mayastor:
>   csi:
>     node:
>       initContainers:
>         enabled: true
**>   etcd:
>     # -- Kubernetes Cluster Domain
>     clusterDomain: acme.lab
>     nodeSelector:
>       openebsetc: 'true'
>     tolerations:
>       - key: node-role.kubernetes.io/control-plane
>         operator: Exists
>       - key: node-role.kubernetes.io/master
>         operator: Exists**
>   localpv-provisioner:
>     enabled: false
>   crds:
>     enabled: false
> 
> preUpgradeHook:
>   image:
>     # -- The container image registry URL for the hook job
>     registry: docker.io
>     # -- The container repository for the hook job
>     repo: bitnami/kubectl
>     # -- The container image tag for the hook job
>     tag: "1.25.15"
>     # -- The imagePullPolicy for the container
>     pullPolicy: IfNotPresent
> 
> engines:
>   local:
>     lvm:
>       enabled: true
>     zfs:
>       enabled: true
>   replicated:
>     mayastor:
>       enabled: true


The etcd pods are now running on 3 different master nodes. But all 3 still report the same error:

> ERROR ==> Headless service domain does not have an IP per initial member in the cluster


I checked the output of the pods but there are no more obvious errors. just:

>  state:
>       waiting:
>         message: back-off 1m20s restarting failed container=etcd pod=openebs-etcd-2_openebs(6f5821c0-4522-46fd-a7b7-c040090cd79c)
>         reason: CrashLoopBackOff


I also checked the IPs, all pods got IPs:

> kubectl exec -i -t dnsutils -- nslookup kubernetes.default
> kubectl exec -ti dnsutils -- cat /etc/resolv.conf
> kubectl exec -ti dnsutils -- nslookup openebs-etcd-headless.openebs.svc.cluster.local
> kubectl exec -ti dnsutils -- nslookup openebs-etcd-headless.openebs.svc.acme.lab
> Server:         172.30.0.10
> Address:        172.30.0.10#53
> 
> Name:   kubernetes.default.svc.cluster.local
> Address: 172.30.0.1
> 
> search default.svc.cluster.local svc.cluster.local cluster.local acme.lab
> nameserver 172.30.0.10
> options ndots:5
> Server:         172.30.0.10
> Address:        172.30.0.10#53
> 
> Name:   openebs-etcd-headless.openebs.svc.cluster.local
> Address: 10.129.0.58
> Name:   openebs-etcd-headless.openebs.svc.cluster.local
> Address: 10.128.0.50
> Name:   openebs-etcd-headless.openebs.svc.cluster.local
> Address: 10.130.0.52
> 
> Server:         172.30.0.10
> Address:        172.30.0.10#53
> 
> Name:   openebs-etcd-headless.openebs.svc.acme.lab
> Address: 10.82.28.10


I checked the services, too. The openebs-etcd-headless has no clusterIP, as expected, and the etcd pods are attached to this service and the service that has clusterIPs.


I set the ETCD_INITIAL_CLUSTER_STATE to "existing" but then all etcd pods report:
> WARN ==> Cluster not healthy, not adding self to cluster for now, keeping trying...


Also changing the replica count does not help.

**Comment by FamilieRo** [comment]
Setting BITNAMI_DEBUG to true I get one extra line in the log output:

> etcd 10:39:44.65
> etcd 10:39:44.65 Welcome to the Bitnami etcd container
> etcd 10:39:44.65 Subscribe to project updates by watching https://github.com/bitnami/containers
> etcd 10:39:44.66 Submit issues and feature requests at https://github.com/bitnami/containers/issues
> etcd 10:39:44.66
> etcd 10:39:44.66 INFO ==> ** Starting etcd setup **
> etcd 10:39:44.67 INFO ==> Validating settings in ETCD_* env vars..
> etcd 10:39:44.67 WARN ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
> etcd 10:39:44.67 INFO ==> Initializing etcd
> etcd 10:39:44.68 INFO ==> Generating etcd config file using env variables
> etcd 10:39:44.69 INFO ==> There is no data from previous deployments
> etcd 10:39:44.69 INFO ==> Bootstrapping a new cluster
**> etcd 10:39:44.69 DEBUG ==> Waiting for the headless svc domain to have an IP per initial member in the cluster**
> etcd 10:40:44.75 ERROR ==> Headless service domain does not have an IP per initial member in the cluster

**Comment by tiagolobocastro** [comment]
I think the initial cluster state should be "new" in this case.
But I don't understand why it doesn't work now that all pods are running.
May I suggest uninstalling the chart, and also ensuring there's no etcd pvc and pv leftover:
`helm uninstal ....`
`kubectl -n openebs delete pvc --all`
`kubectl get pv` -> should have none of ours

Then install again, with your custom values

**Comment by FamilieRo** [comment]
Hi,
I cleared up everything and installed openEbs again. Sadly no luck, still the same error.

**Comment by tiagolobocastro** [comment]
Ah, on your message above I see only one ip on the acme.lab domain?
Could you share again `kubectl -n openebs get ep openebs-etcd-headless -o yaml` ?

**Comment by FamilieRo** [comment]
Every pod has it's own IP:

> kubectl -n openebs get ep openebs-etcd-headless -o yaml
> apiVersion: v1
> kind: Endpoints
> metadata:
>   creationTimestamp: "2024-12-12T12:21:16Z"
>   labels:
>     app.kubernetes.io/instance: openebs
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/name: etcd
>     helm.sh/chart: etcd-8.6.0
>     service.kubernetes.io/headless: ""
>   name: openebs-etcd-headless
>   namespace: openebs
>   resourceVersion: "44359046"
>   uid: b94039f7-0a85-4012-9184-f3d63a5dd7ad
> subsets:
> - addresses:
>   - hostname: openebs-etcd-0
>     ip: 10.128.0.115
>     nodeName: <master node 2>
>     targetRef:
>       kind: Pod
>       name: openebs-etcd-0
>       namespace: openebs
>       uid: 871d0211-c2a4-4f93-ad08-556122fa8175
>   - hostname: openebs-etcd-1
>     ip: 10.129.0.63
>     nodeName: <master node 3>
>     targetRef:
>       kind: Pod
>       name: openebs-etcd-1
>       namespace: openebs
>       uid: 0e00fff4-d41e-49b7-a526-bce11000502b
>   - hostname: openebs-etcd-2
>     ip: 10.130.0.59
>     nodeName: <master node 1>
>     targetRef:
>       kind: Pod
>       name: openebs-etcd-2
>       namespace: openebs
>       uid: 0224fa93-66e1-4a82-ac29-dcaf19780040
>   ports:
>   - name: peer
>     port: 2380
>     protocol: TCP
>   - name: client
>     port: 2379
>     protocol: TCP

**Comment by tiagolobocastro** [comment]
Sorry, I had meant to ask for:
`kubectl exec -ti dnsutils -- nslookup openebs-etcd-headless.openebs.svc.acme.lab`

**Comment by FamilieRo** [comment]
@tiagolobocastro: Thanks to your hint I found the problem.

Now, I got openEbs up and running. I set the clusterDomain for etcd to the name of my OpenShift cluster but when asking DNS I only got one IP, the IP from our loadbalancer. When I asked for openebs-etcd-headless.openebs.svc.cluster.local I got all 3 IPs from the pods. So I uncommented the line for clusterDomain and now all 3 pods are up and running. 

I also tried to disable the callinghome pod with setting it to false in my values.yaml:

> obs:
>   callhome:
>     enabled: false

But it was deployed anyway. But it doesn't matter, I deleted the delpoyment for it so the pod is gone and everything seems to be fine now.

**Comment by tiagolobocastro** [comment]
> @tiagolobocastro: Thanks to your hint I found the problem.
> 
> Now, I got openEbs up and running. I set the clusterDomain for etcd to the name of my OpenShift cluster but when asking DNS I only got one IP, the IP from our loadbalancer. When I asked for openebs-etcd-headless.openebs.svc.cluster.local I got all 3 IPs from the pods. So I uncommented the line for clusterDomain and now all 3 pods are up and running.

That's great!
Ah so your K8s is configured with the default clusterDomain cluster.local

> 
> I also tried to disable the callinghome pod with setting it to false in my values.yaml:
> 
> > obs:
> > callhome:
> > enabled: false
> 
> But it was deployed anyway. But it doesn't matter, I deleted the delpoyment for it so the pod is gone and everything seems to be fine now.

That's not expected, if you deploy with callhome not enabled, it should not be deployed. If you try this again and the same happens please do raise an issue for this. Thanks!

**Comment by vistralmystral** [comment]
I just wanted to add this information for others who experience the issue with `openebs-etcd-{NUM}` pods failing to start with `Headless service domain does not have an IP per initial member in the cluster` error. 

In my case I had a cluster of two Kubernetes nodes (`kubectl get nodes`) on the default cluster dns name `cluster.local`. The openebs helm chart (`helm install openebs --namespace openebs openebs/openebs --create-namespace`) installs 3 `openebs-etcd-{NUM}` pods (E.g. `openebs-etcd-0`, `openebs-etcd-1`, `openebs-etcd-2`) as part of a statefulset and the definition for this statefulset (`kubectl edit statefulset openebs-etcd -n openebs`) has an `antiAffinity` which, if I read it correctly, allows only one `openebs-etcd-{NUM}` pod per k8s node to be scheduled: 

```
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: openebs
                app.kubernetes.io/name: etcd
            topologyKey: kubernetes.io/hostname
```

So in a two node k8s cluster, one pod could never be properly scheduled. Changing the number of replicas to the number of k8s nodes to 2 in the statefulset still didn't resolve the error and this looks like it's because the `openebs-etcd` statefulset passes environment variables to the Bitnami etcd process which bootstrap the cluster by expecting 3 pods to be present. 

Specifically: 

```
        - name: ETCD_INITIAL_CLUSTER
          value: openebs-etcd-0=http://openebs-etcd-0.openebs-etcd-headless.openebs.svc.cluster.local:2380,openebs-etcd-1=http://openebs-etcd-1.openebs-etcd-headless.openebs.svc.cluster.local:2380,openebs-etcd-2=http://openebs-etcd-2.openebs-etcd-headless.openebs.svc.cluster.local:2380
```

If any one of the pods doesn't respond (E.g. because it's not scheduled), Bitnami fails to bootstrap on any other instance of the pod and throws `Headless service domain does not have an IP per initial member in the cluster`. 

!NOTE: Additional errors after bootstrap about a cluster mismatch will occur if the pods have already created their persistent volumes (see: https://github.com/ahrtr/etcd-issues/blob/master/docs/cluster_id_mismatch.md)  

I fixed this by manually amending the `openebs-etc` statefulset (`kubectl edit statefulset openebs-etcd -n openebs`) spec. These are the exact steps:

1) First setting the number of replicas to 0 to scale down the statefulset and remove all the pods:

```
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 0 # Changed from 3
  revisionHistoryLimit: 10
  selector:
```

2) Amend the `ETCD_INITIAL_CLUSTER` enviornment variable in the same spec to match the number of pods (replicas) that will be scheduled (since there are only two k8s nodes, in this example there will only be 2):

```
        - name: ETCD_INITIAL_CLUSTER
          value: openebs-etcd-0=http://openebs-etcd-0.openebs-etcd-headless.openebs.svc.cluster.local:2380,openebs-etcd-1=http://openebs-etcd-1.openebs-etcd-headless.openebs.svc.cluster.local:2380 # removed openebs-etcd-2 [...]
```

3) Save the changes to the spec

4) Delete the pod volume claims to avoid cluster id mismatch (See how cluster ids are resolved in link above): 

```
kubectl delete pvc data-openebs-etcd-0 data-openebs-etcd-1 data-openebs-etcd-2 -n openebs
```

5)  ...and the persistent volumes backing them

```
kubectl get pv -n openebs | grep Released | awk '{print $1}' | xargs kubectl delete pv -n openebs
```

6) Scale back up the stateful set by editing `kubectl edit statefulset openebs-etcd -n openebs` and amending replicas to 2:

```
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 2 # Changed from 0
  revisionHistoryLimit: 10
  selector:
```

7) Save changes and view the pods re-initialization: `kubectl get pods -n openebs`

Watching the logs on either pod 0 or 1 `kubectl logs -f openebs-etcd-0 -n openebs` should show them successfully bootstrap and eventually reach a READY 1/1 state per pod. 

This fixed the issue and shortly thereafter everything else spun up correctly. 

Sidenote: Upgrading or reinstalling with `helm` will probably overwrite the changes, so you'd likely have to make them each time, create a patch to apply them or update the helm chart.
