### ISSUE TITLE
container security scanner marks the mayastor images as unsupported. 

### ISSUE THREAD

**Issue by kmova** [openebs/Mayastor#238]
**Describe the bug**

Both trivy based container scanning and quay image scanner report the mayastor container images as unsupported. 

**To Reproduce**

The quay.io status can be seen here: https://quay.io/repository/openebs/moac?tab=tags

To test with trivy, you can use the following steps. 
- Download Trivy 
- Download the mayastor container image
- Scan the image using Trivy as follows:
  `$ ./trivy  --exit-code 1 --severity CRITICAL --no-progress openebs/moac:0.1.0`
  
   The output looks like:

   ```
   2020-05-16T02:20:51.566Z        FATAL   error in image scan: scan failed: failed to apply layers: unknown OS
   ```

**Expected behavior**
Scanning should complete without errors. 

**Screenshots**

** OS info (please complete the following information):**
 - Distro: [e.g. NixOS]
 - Kernel version
 - MayaStor revision or container image: 0.1.0 version for all mayastor container images. 

**Additional context**
Though nix images are secure, some platforms like AWS Marketplace, RH expect the containers to pass their certification test. Raising this issue to help verify if images can be uploaded to AWS Marketplace for running with EKS platforms.  ( cc: @muratkars )

Also may need to investigate if an issue needs to raised against https://github.com/aquasecurity/trivy to allow trivy to pass the nix based container images.

**Comment by muratkars** [comment]
Thanks for point out @kmova . I get a similar message when the image is upload to AWS ECR for security scanning. 
![AWS_Marketplace](https://user-images.githubusercontent.com/1729024/82109788-b79a9c00-96ed-11ea-9117-1bd709dd730c.PNG)

**Comment by gila** [comment]
Our container images are not based on any os. 

Both scanners seem to be looking for a base os image, which we don’t have and don’t need.

**Comment by gila** [comment]
closing this issue for now as there is nothing wrong or insecure with our images.
