### ISSUE TITLE
Potential shadow file exposed

### ISSUE THREAD

**Issue by ikaustubhk** [openebs/Mayastor#269]
Hello Team,

While checking I came across a potential shadow file that is exposed to this repository. Please check on the below path and restrict the file according to its criticality.

Path to file: https://github.com/openebs/Mayastor/blob/master/nix/pkgs/ms-buildenv/root/etc/shadow

Attaching screenshot of the same. 
![shadowfile_poc](https://user-images.githubusercontent.com/20518692/84016731-50de6a80-a99b-11ea-8af2-1bb61c3c219d.PNG)

**Comment by jkryl** [comment]
Hi @ikaustubhk , this file isn't distributed as part of mayastor. It is only part of mayastor build environment container that is used for running CI/CD. So it cannot cause any kind of security issue in mayastor product. I'm closing the ticket. Feel free to re-open it in case that you are not happy with my answer.
