### ISSUE TITLE
Block Device On Minio

### ISSUE THREAD

**Issue by sstubbs** [openebs/Mayastor#309]
**Is your feature request related to a problem? Please describe.**
I currently am using local pvs for a few stateful containers and it is working well. two of which are cyrus imap and minio.

**Describe the solution you'd like**
Use a block device on top of minio for storing maildir email messages. I saw in the project description that this is a possible feature in the future.

**Describe alternatives you've considered**
I can use the clustering built into cyrus imap using local pvs as I am doing for other applications that provide clustering.

**Additional context**
This is more out of curiousity than anything else as I really like minio and would like to leverage it for email if possible.

**Comment by gila** [comment]
@sstubbs We are indeed still planning to add support for using an s3 bucket as a block device. However, we have not started that work yet. We would need to write code that will handle submission and completion to s3 bucket and abstract within the new bdev. We have not yet started any work on this as of today.

**Comment by sstubbs** [comment]
ok thanks happy to hear it's something being planned for.
