### ISSUE TITLE
[Doc Source]: Typo in "Deploy the FIO Test Pod" section

### ISSUE THREAD

**Issue by rohan2794** [openebs/Mayastor#427]
**Are you reporting an issue with existing content?**
There is typo in **kubectl** command for Deploy the FIO Test Pod section, **kubect** is present in place of **kubectl** at two occurrences. 

Existing : `kubect` apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/fio.yam
Expected: `kubectl `apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/fio.yam

Existing: `kubect` get pod fio
Expected: `kubectl` get pod fio

Link of the affected page(s): [deploy-the-fio-test-pod](https://mayastor.gitbook.io/introduction/quickstart/deploy-a-test-application#deploy-the-fio-test-pod)

**Are you proposing new content, or a change to the existing documentation layout or structure?**
Please describe your proposal.

**Comment by GlennBullingham** [comment]
Thanks for raising this Rohan.  Both typos have now been corrected.
