### ISSUE TITLE
[Doc Source]: namespace yaml is in JSON format and incorrect value of "minimum" in mayastorpoolcrd.yaml

### ISSUE THREAD

**Issue by rohan2794** [openebs/Mayastor#432]
**Are you reporting an issue with existing content?**

Basically, namespace.yaml is in JSON format in **YAML** tab
Link of the affected page: [namespace](https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor#application-namespace)

In  mayastorpoolcrd.yaml , at line number 78, expected value of **minimum** is int `0` but mention string `are` in **YAML** tab and giving error when user apply mayastorpoolcrd.yaml.
Link of the affected page: [mayastorpoolcrd](https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor#mayastor-custom-resource-definitions)

In Control Plane section, `.yaml` is missing from `kubectl apply -f moac-deployment` in **Command (local repo)** tab
Link of the affected page: [moac-deployment](https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor#control-plane)

**Are you proposing new content, or a change to the existing documentation layout or structure?**
Please describe your proposal.

**Comment by GlennBullingham** [comment]
Thanks again Rohan, I've updated the affected pages to correct these errors.
