### ISSUE TITLE
Openshift / OKD support (RHCOS/FCOS)

### ISSUE THREAD

**Issue by Born2Bake** [openebs/mayastor#436]
**Feature request**
Additional docs for deployment on Openshift / OKD, CoreOS machines.

**Describe the solution**
If you create scc's for moac/moac-csi service accounts, mayastor can run in openshift; example - http://paste.openstack.org/show/798355/

P.S. It is worth to add in the docs that if you run k8s cluster on virtual machines; those need to support "+ssse3,+sse4.1,+sse4.2" cpu modules.

**Comment by gila** [comment]
@Born2Bake Thank you for the suggestion, adding the CPU instruction set to our docs is indeed far less ambiguous. Right now we just refer to Nehalem or later. 

Obviously, the adding the example openshift YAML is very nice too - thanks 👍

**Comment by immanuelfodor** [comment]
When using Proxmox QEMU/KVM, the extra CPU args field overrides the CPU configuration set up on the web interface, so you need to add those as well to the args field. For example:

```
qm set 100 --args "-cpu 'kvm64,+aes,enforce,-hv-evmcs,+kvm_pv_eoi,+kvm_pv_unhalt,+lahf_lm,+md-clear,+pcid,+sep,+spec-ctrl,+ssbd,+ssse3,+sse4.1,+sse4.2,+x2apic'"
```
