### ISSUE TITLE
MSP replicas are not cleared as expected

### ISSUE THREAD

**Issue by gila** [openebs/Mayastor#437]
***Describe the bug***

When deleting a replica the data is not removed as expected.

***To Reproduce***

1) create a replica, format it with your favourite FS, delete the replica. 
 2) create a new replica, observe the old replica is returned

***Expected behaviour***

Replicas should be zeroed out

**Comment by gila** [comment]
This issue also comes up when we create/destroy pools as we do not wipe out any of the metedata.

**Comment by jonathan-teh** [comment]
This could not be reproduced, deleting replicas or deleting pools with replicas present was observed to write zeros to the replica data followed by removing the replica metadata. The same thing was observed in Kubernetes when deleting a PVC that uses a storage class with 2 replicas and the nvmf protocol. The behaviour is consistent with Mayastor running on 2 cores (`-m 0x3`).
