### ISSUE TITLE
Different block size of nexus and child dev should not fail the nexus create request

### ISSUE THREAD

**Issue by jkryl** [openebs/MayaStor#51]
We tripped over the following problem:
```
nexus_child.rs: 103:: *ERROR*: nexus-32b154c1-6bf9-4021-a3e1-bb2d09df407e: Invalid block size for bdev:///32b154c1-6bf9-4021-a3e1-bb2d09df407e, wanted: 4096 got 512
jsonrpc.rs: 185:: *ERROR*: failed to create nexus
```
it is suboptimal if the block sizes are different but perhaps not fatal. Explore and test if the check can be removed and replaced by a log message.

**Comment by jkryl** [comment]
After pushing https://github.com/openebs/MayaStor/pull/53 this becomes a less urgent issue. It cannot happen that the block size of nexus and replica would be different (4k for all). Though this holds true only until external replicas with arbitrary block sizes are supported. In any case, when we get to implementing this feature we need to understand implications in terms of performance and it must be covered by test cases.

**Comment by gila** [comment]
This should be fixed now with the integration of 
449ee4c
