### ISSUE TITLE
Ability to auto-create Mayastor pools 

### ISSUE THREAD

**Issue by kmova** [openebs/mayastor#519]
**Is your feature request related to a problem? Please describe.**
I need a better way to automate the bringing up of Kubernetes Clusters with Mayastor configured. I use Cluster API to setup the Kubernetes cluster that takes care of setting up the nodes with the prerequisites to run Mayastor. As part of the Mayastor installation, labelling the nodes, I should be able to specify what devices should be used to create Mayastor pools automatically, instead of me having to add a node, label a node, fetch devices and create a MSP. I am looking to avoid the steps => fetch devices and create MSP. 

**Describe the solution you'd like**
It should be as simple as labeling the node with devices to be used to create MSP. 

**Describe alternatives you've considered**
Still exploring

**Additional context**
Creating this issue based on the discussion started in the [Kubernetes Slack thread](https://kubernetes.slack.com/archives/CUAKPFU78/p1605225147238700)

**Comment by bobek** [comment]
@rawkode, can you please provide details about your use-case? We do currently use a custom resource for pool definition. For example (taken from [terrafor experiment](https://github.com/mayadata-io/mayastor-terraform-playground/blob/main/hcloud-kubeadm/modules/mayastor/templates/mayastor-pool-local.yaml) we are currently working on):

```
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: mayastor-pool-local-${node}
  namespace: mayastor
spec:
  node: ${node}
  disks:
    - /dev/sdb
```

Thus creating a pool is quite straightforward. I can imagine, that we can introduce a `nodeSelector` as is usual at deployments and such. Just be aware, that currently pool to nodes is a 1:1 relationship, so matching multiple nodes will result in having multiple pools.

Do you use any k8s/configuration automation for your deployment?
