### ISSUE TITLE
It takes a very long time to reboot a node with app using nvmf mayastor volume

### ISSUE THREAD

**Issue by jkryl** [openebs/Mayastor#556]
I have reproduced this twice when testing nexus failover and it seems to be always the case when rebooting a node with an application using a mayastor volume. We suspect that nvmf connection from the initiator to nexus target is preventing the node from getting rebooted. It eventually reboots but after a very long time like 15 minutes or so. I'm not sure if we can do something about it but at least we should understand why that happens.

**Comment by bobek** [comment]
FYI console screenshot when server is gracefully rebooted 
![image](https://user-images.githubusercontent.com/26891/101086175-c45ede80-35b0-11eb-99b2-a7ff858ecd76.png)

**Comment by gila** [comment]
So it seems that our teardown path is not correct, that is to say during reboot, the containers are not shut down in sequence and its, for the most part, a big mess. It will reboot eventually, I suppose...

**Comment by gila** [comment]
Im closing this issue here as there isn't much we can do about it.
