### ISSUE TITLE
Improve lifecycle of the deployment configuration

### ISSUE THREAD

**Issue by bobek** [openebs/Mayastor#569]
We have a problem that we have to maintain a duplicate set of yamls for deploying mayastor in our e2e tests. Also there is a separate repository for [OpenEBS Helm Charts](https://github.com/openebs/charts/). Instead we would like to have template yamls that we can configure for whatever use case we have (user, developer, ci/cd, …). Sounds like a perfect job for Helm, but we also use Terraform for deployments, so need to find a good integration setup.

## Possible approaches
* Use original YAMLs - change images via sed - deploy using kubectl/terraform
  * One copy of kubectl yamls
* Use original YAMLs - use kubectl patch - deploy via terraform
  * One copy of kubectl yamls
  * Not very nice as patch will result in redeploys within infrastructure (which costs time, but also changes state)
* Use original YAMLs - apply kustomize.yaml - deploy using kubectl/terraform
  * One copy of kubectl yamls
* Create helm chart - apply variables (via helm) - deploy using helm/terraform
  * Two copies - yamls + helm | drop original yamls and force users to use helm
  * Needs maintenance - importing original yaml changes
* Create native terraform templates (HCL autogenerate) - deploy using terraform
  * Needs maintenance - regeneration on original yaml change
* (CHOSEN SOLUTION) Generate YAMLs from common template (terraform/jinja/helm/sed) - generate deploy/* + generate terraform (or e2e yamls) and anything that comes in our way - deploy however
  * Needs to be run in CI and committed to git to `develop` and to `master` and `openebs/charts`
  * E2e tests will run the “engine” and generate deploy yamls for itself
* Generate yamls from TF code
  * Strange - not supported workflow - might be possible
  * Not sure it can be done nicely with TF - probably above (common source and generate two is better)
* Use NIX

## Selected approach

As marked, we have chosen the pretty standard approach of `template -> render -> artifact` approach. While there is plenty of possible templating engines out there, we have chose `helm` as that will give us help charts for free and it is a well known tool for the k8s comunity. Quick prototype shows that this should be pretty feasible way.

**Comment by GlennBullingham** [comment]
Removed the documentation label, since this issue doesn't refer to a suggestion/issue with the user documentation at GitBook.io

**Comment by bobek** [comment]
Sorry for the noise, but this became a duplicate of #570
