### ISSUE TITLE
How to set up k8s snapshots with mayastor volumes? 

### ISSUE THREAD

**Issue by RandomGHUser** [openebs/Mayastor#785]
I have not been able to find comprehensive documentation on taking regular snapshots of mayastor volumes nor how to set up snapshotting of these volumes via velero.  Is this possible, and if so, is there any documentation?

**Comment by GlennBullingham** [comment]
Hi @RandomGHUser, and thanks for your interest in Mayastor.   The reason for the lack of documentation in this area is that snapshot support for Mayastor volumes has not been implemented yet, and hence isn't available to be leveraged by Velero.  As new features and functionality are added to Mayastor, they will be documented in the [official documentation](https://mayastor.gitbook.io/introduction/)
