### ISSUE TITLE
Mounted Volume permisions not set for fsGroup

### ISSUE THREAD

**Issue by bbroniewski** [openebs/Mayastor#822]
**Describe the bug**
After volume creation Kubernetes should change owner of the volume directories to group specified by fsGroup in pod "spec" field, but it is not happening. The same works fine with cStor engine.

**To Reproduce**
My cluster setup is:
-Flannel CNI - Layer 2
-Metallb - Load Balancer
-Openebs Mayastor with disk attached to the device using protocol iscsi
-One node

Configuration of default StorageClass and Mayastor tested using "Fio" pod.

During installation of Kyma, resource "ory" initiates a postgresql database with pvc which require 8GB pv.
Mayastor assigns PV and all Mayastor objects are healthy.

Docker container is trying to create directory using "mkdir" command and it is failing:
"mkdir: can't create directory '/data/pgdata': Permission denied"

**Expected behavior**
Directory should be created, because mounted directories should have group specified in "fsGroup" as owner.

**Screenshots**
![image](https://user-images.githubusercontent.com/11493147/113049624-249f0f00-91a4-11eb-9ee7-6d0ba60af57d.png)
![image](https://user-images.githubusercontent.com/11493147/113049701-3d0f2980-91a4-11eb-989f-84d260db7a0d.png)

** OS info (please complete the following information):**
Ubuntu Server 20.04
 - Kernel version 5.4.0-70-generic
 - MayaStor revision 0.8

**Additional context**
Link to the thread on slack:
https://kubernetes.slack.com/archives/CUAKPFU78/p1616749885288800

**Comment by jkryl** [comment]
@bbroniewski thanks for the ticket! We need to find out why securityContext fsGroup does not work with mayastor. It has been verified to work with cstor. The investigation is in progress.

**Comment by kschzt** [comment]
I have a very similar issue with TimescaleDB (PostgreSQL), the fsGroup is not honored and the pod fails trying to create the /var/lib/postgresql/data folder.

**Comment by payes** [comment]
hi @kschzt @bbroniewski , can you please try adding fsType in parameters section of storage class. Something similar to:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mayastor-nvmf
parameters:
  repl: '3'
  protocol: 'nvmf'
  fsType: 'xfs'
provisioner: io.openebs.csi-mayastor
```

**Comment by kschzt** [comment]
@payes Happy to confirm that setting `fsType` worked! Thanks!

**Comment by bbroniewski** [comment]
Will test it, thank you! @payes
