### ISSUE TITLE
Implement hold on channels

### ISSUE THREAD

**Issue by gila** [openebs/MayaStor#9]
When we online a child we need a reference to the IO channels. Right now this is implemented as:

```rust
let ch = get_io_channel()
... code
put_io_channel(ch)
```

It would be nice if we can do a simple `self.channel.hold()` or something like that

**Comment by gahag** [comment]
Can I work on this? I've found the definition of `get_io_channel`, but didn't manage to find `put_io_channel`. Any tips?

**Comment by gila** [comment]
hi, @gahag for sure! 

The section I'm referring to is implemented here

https://github.com/openebs/MayaStor/blob/185c649dab178637dadcfb9a475cf977ee533f03/mayastor/src/bdev/nexus/nexus_bdev_children.rs#L99

When process the "DR" event, and then we do:

https://github.com/openebs/MayaStor/blob/185c649dab178637dadcfb9a475cf977ee533f03/mayastor/src/bdev/nexus/nexus_bdev_children.rs#L101

Ideally, we would not have to do this step manually (as when forgotten, the event is not processed) and, we would like to prevent any calls to `unsafe{}` directly in any file that starts with `nexus_`. (the abstractions could be placed in `mod.rs` for example.

Let me know if you require any more help!

**Comment by gahag** [comment]
I'm halfway with the implementation, but I'm having some difficulty with building the project. I've read the build guide, and I have a few questions. First, I'm on arch linux with the LTS kernel, sitting at version 4.19. Am I required to switch to the mainline kernel (5.3.7)? Also, how can I build using docker?

**Comment by gila** [comment]
Hi Gahag.

No, you don't need to move to 5.x kernels. That is only needed when you are trying to attach over nvmf-tcp. 

In order to use docker, you can pull our development container as described here: https://github.com/openebs/MayaStor/blob/master/doc/build.md#build-in-side-docker

Let me know if that helps!

**Comment by gahag** [comment]
Thanks for the tips! I've managed to get things almost working with the docker image. I had to update the rust toolchain to get some dependencies to compile, but I'm getting a link error on mayastor:

> error: linking with `cc` failed: exit code: 1
>   |
>   = note: /usr/bin/ld: /root/MayaStor/target/debug/deps/libmayastor-96c3dba6c179a74d.rlib(mayastor-96c3dba6c179a74d.4p
> i9smpals94548h.rcgu.o): in function `mayastor::bdev::nexus::nexus_share::<impl mayastor::bdev::nexus::nexus_bdev::Nexu
> s>::share::{{closure}}':
>           /root/MayaStor/mayastor/src/bdev/nexus/nexus_share.rs:45: undefined reference to `create_crypto_disk'
>           /usr/bin/ld: /root/MayaStor/target/debug/deps/libmayastor-96c3dba6c179a74d.rlib(mayastor-96c3dba6c179a74d.4p
> i9smpals94548h.rcgu.o): in function `mayastor::bdev::nexus::nexus_share::<impl mayastor::bdev::nexus::nexus_bdev::Nexu
> s>::unshare::{{closure}}':
>           /root/MayaStor/mayastor/src/bdev/nexus/nexus_share.rs:92: undefined reference to `delete_crypto_disk'
>           collect2: error: ld returned 1 exit status

But i don't think we have to solve this immediately, as compiling is enough for this matter. I'll send an initial version of my patch for review. Thanks for your attention by the way.

**Comment by gila** [comment]
On Wed, Oct 23, 2019 at 8:08 PM gahag <notifications@github.com> wrote:

> Thanks for the tips! I've managed to get things almost working with the
> docker image. I had to update the rust toolchain to get some dependencies
> to compile, but I'm getting a link error on mayastor:
>
> error: linking with cc failed: exit code: 1
> |
> = note: /usr/bin/ld:
> /root/MayaStor/target/debug/deps/libmayastor-96c3dba6c179a74d.rlib(mayastor-96c3dba6c179a74d.4p
> i9smpals94548h.rcgu.o): in function mayastor::bdev::nexus::nexus_share::<impl
> mayastor::bdev::nexus::nexus_bdev::Nexu s>::share::{{closure}}':
> /root/MayaStor/mayastor/src/bdev/nexus/nexus_share.rs:45: undefined
> reference to create_crypto_disk'
> /usr/bin/ld:
> /root/MayaStor/target/debug/deps/libmayastor-96c3dba6c179a74d.rlib(mayastor-96c3dba6c179a74d.4p
> i9smpals94548h.rcgu.o): in function mayastor::bdev::nexus::nexus_share::<impl
> mayastor::bdev::nexus::nexus_bdev::Nexu s>::unshare::{{closure}}':
> /root/MayaStor/mayastor/src/bdev/nexus/nexus_share.rs:92: undefined
> reference to delete_crypto_disk'
> collect2: error: ld returned 1 exit status
>
>  I've actually just updated the docs because it indeed is something that
requires some explanation! The container image comes pre-packed with a
library (libspdkfat.so) which is somewhat outdated now. To get it up to
date, within the container:

cd spdk-sys
git submodule update --init --recursive
./build.sh --enable-debug --without-isal --with-iscsi-initiator --with-rdma
\
             --with-internal-vhost-lib --disable-tests \
             --with-crypto
cp build/libspdk_fat.so /lib

Then it should work :)


> But i don't think we have to solve this immediately, as compiling is
> enough for this matter. I'll send an initial version of my patch for
> review. Thanks for your attention by the way.
>

My pleasure and thanks to you too!
