### ISSUE TITLE
Does mayastor pool support RWX ?

### ISSUE THREAD

**Issue by everydots** [openebs/Mayastor#915]

**Comment by GlennBullingham** [comment]
No.  At this time, only RWO is supported for Mayastor Volumes.  Support may be added in future releases.  Consider though that Mayastor is fundamentally a block-based storage sub-system, and RWX within that context doesn't equate directly with a shared/clustered file system (e.g. NFS, Gluster), if that is the functionality which you are seeking.

**Comment by everydots** [comment]
thanks very much for clarity:)
